// GENERATED by scripts/gen_local_schema.mjs — do not edit by hand.
// Re-run it after any migration that adds a column default, a moddatetime
// trigger or a foreign key; `localSchema.test.ts` fails if you forget.
//
// This is the part of the database a LOCAL project has to reproduce without a
// database. Postgres fills defaults, moves `updated_at`, cascades deletes and
// derives `project_id` on the cloud plane; on the local plane this file plus
// `localStore.ts` are the whole of that behaviour.

/** How to fill a column the caller left out. `now`/`uuid` are computed per
 *  row; `value` is a constant (deep-copied before it is written, or two rows
 *  would share one `meta` object). */
export type ColumnDefault =
  | { kind: "now" }
  | { kind: "uuid" }
  | { kind: "value"; value: unknown };

/** Every table a local project is made of: the owned tables, minus the
 *  series-rooted v1 ones — no project sits above those, so they can never be
 *  part of a project that lives on this machine. */
export const LOCAL_TABLES: readonly string[] = [
  "assets",
  "beats",
  "bible_assets",
  "bible_entries",
  "bible_revisions",
  "block_takes",
  "chat_messages",
  "chat_threads",
  "clips",
  "collection_assets",
  "collections",
  "cost_ledger",
  "custom_workflows",
  "episodes",
  "generation_blocks",
  "jobs",
  "projects",
  "rag_chunks",
  "rag_documents",
  "scenes",
  "storyboards",
  "take_assemblies",
  "take_reviews",
  "timelines",
  "tracks",
  "voice_clones"
];

export const LOCAL_TABLE_SET: ReadonlySet<string> = new Set(LOCAL_TABLES);

/** table -> column -> what Postgres would have filled in. */
export const DEFAULTS: Readonly<Record<string, Record<string, ColumnDefault>>> = {
  "assets": {
    "created_at": {
      "kind": "now"
    },
    "hidden": {
      "kind": "value",
      "value": false
    },
    "id": {
      "kind": "uuid"
    },
    "meta": {
      "kind": "value",
      "value": {}
    },
    "origin": {
      "kind": "value",
      "value": "generated"
    },
    "tags": {
      "kind": "value",
      "value": []
    }
  },
  "beats": {
    "id": {
      "kind": "uuid"
    },
    "meta": {
      "kind": "value",
      "value": {}
    }
  },
  "bible_assets": {
    "role": {
      "kind": "value",
      "value": "ref"
    },
    "slot": {
      "kind": "value",
      "value": 0
    }
  },
  "bible_entries": {
    "created_at": {
      "kind": "now"
    },
    "doc": {
      "kind": "value",
      "value": {}
    },
    "id": {
      "kind": "uuid"
    },
    "status": {
      "kind": "value",
      "value": "draft"
    },
    "updated_at": {
      "kind": "now"
    },
    "version": {
      "kind": "value",
      "value": 1
    }
  },
  "bible_revisions": {
    "created_at": {
      "kind": "now"
    },
    "id": {
      "kind": "uuid"
    },
    "proposed_by": {
      "kind": "value",
      "value": "director"
    }
  },
  "block_takes": {
    "created_at": {
      "kind": "now"
    },
    "id": {
      "kind": "uuid"
    },
    "kind": {
      "kind": "value",
      "value": "master"
    },
    "state": {
      "kind": "value",
      "value": "pending"
    }
  },
  "chat_messages": {
    "created_at": {
      "kind": "now"
    },
    "id": {
      "kind": "uuid"
    },
    "streaming": {
      "kind": "value",
      "value": false
    }
  },
  "chat_threads": {
    "brief": {
      "kind": "value",
      "value": {}
    },
    "created_at": {
      "kind": "now"
    },
    "id": {
      "kind": "uuid"
    },
    "kind": {
      "kind": "value",
      "value": "director"
    },
    "updated_at": {
      "kind": "now"
    },
    "wizard": {
      "kind": "value",
      "value": {}
    }
  },
  "clips": {
    "audio_detached": {
      "kind": "value",
      "value": false
    },
    "audio_fx": {
      "kind": "value",
      "value": []
    },
    "created_at": {
      "kind": "now"
    },
    "gain_db": {
      "kind": "value",
      "value": 0
    },
    "id": {
      "kind": "uuid"
    },
    "in_ms": {
      "kind": "value",
      "value": 0
    },
    "ops": {
      "kind": "value",
      "value": []
    },
    "updated_at": {
      "kind": "now"
    }
  },
  "collection_assets": {
    "added_at": {
      "kind": "now"
    },
    "idx": {
      "kind": "value",
      "value": 0
    }
  },
  "collections": {
    "created_at": {
      "kind": "now"
    },
    "hidden": {
      "kind": "value",
      "value": false
    },
    "id": {
      "kind": "uuid"
    },
    "idx": {
      "kind": "value",
      "value": 0
    },
    "updated_at": {
      "kind": "now"
    }
  },
  "cost_ledger": {
    "estimate": {
      "kind": "value",
      "value": false
    },
    "id": {
      "kind": "uuid"
    },
    "occurred_at": {
      "kind": "now"
    }
  },
  "custom_workflows": {
    "created_at": {
      "kind": "now"
    },
    "id": {
      "kind": "uuid"
    },
    "requirements": {
      "kind": "value",
      "value": {}
    },
    "slots": {
      "kind": "value",
      "value": {}
    },
    "source": {
      "kind": "value",
      "value": "import"
    },
    "status": {
      "kind": "value",
      "value": "draft"
    },
    "updated_at": {
      "kind": "now"
    }
  },
  "episodes": {
    "created_at": {
      "kind": "now"
    },
    "id": {
      "kind": "uuid"
    },
    "idx": {
      "kind": "value",
      "value": 0
    },
    "status": {
      "kind": "value",
      "value": "draft"
    },
    "updated_at": {
      "kind": "now"
    }
  },
  "generation_blocks": {
    "audio_mode": {
      "kind": "value",
      "value": "native"
    },
    "beat_ids": {
      "kind": "value",
      "value": []
    },
    "created_at": {
      "kind": "now"
    },
    "id": {
      "kind": "uuid"
    },
    "mode": {
      "kind": "value",
      "value": "r2v"
    },
    "params": {
      "kind": "value",
      "value": {}
    },
    "ref_plan": {
      "kind": "value",
      "value": []
    },
    "scene_ids": {
      "kind": "value",
      "value": []
    },
    "status": {
      "kind": "value",
      "value": "planned"
    },
    "trim": {
      "kind": "value",
      "value": {}
    },
    "updated_at": {
      "kind": "now"
    }
  },
  "jobs": {
    "attempt": {
      "kind": "value",
      "value": 0
    },
    "cancel_requested": {
      "kind": "value",
      "value": false
    },
    "created_at": {
      "kind": "now"
    },
    "depends_on": {
      "kind": "value",
      "value": []
    },
    "id": {
      "kind": "uuid"
    },
    "lane": {
      "kind": "value",
      "value": "gpu"
    },
    "payload": {
      "kind": "value",
      "value": {}
    },
    "priority": {
      "kind": "value",
      "value": 50
    },
    "progress": {
      "kind": "value",
      "value": 0
    },
    "status": {
      "kind": "value",
      "value": "queued"
    },
    "timing": {
      "kind": "value",
      "value": {}
    },
    "updated_at": {
      "kind": "now"
    }
  },
  "projects": {
    "aspect": {
      "kind": "value",
      "value": "16:9"
    },
    "created_at": {
      "kind": "now"
    },
    "fps": {
      "kind": "value",
      "value": 24
    },
    "genre": {
      "kind": "value",
      "value": []
    },
    "id": {
      "kind": "uuid"
    },
    "settings": {
      "kind": "value",
      "value": {}
    },
    "size_id": {
      "kind": "value",
      "value": "720p"
    },
    "status": {
      "kind": "value",
      "value": "draft"
    },
    "updated_at": {
      "kind": "now"
    }
  },
  "rag_chunks": {
    "id": {
      "kind": "uuid"
    },
    "meta": {
      "kind": "value",
      "value": {}
    }
  },
  "rag_documents": {
    "created_at": {
      "kind": "now"
    },
    "id": {
      "kind": "uuid"
    }
  },
  "scenes": {
    "cast_ids": {
      "kind": "value",
      "value": []
    },
    "created_at": {
      "kind": "now"
    },
    "id": {
      "kind": "uuid"
    },
    "meta": {
      "kind": "value",
      "value": {}
    },
    "status": {
      "kind": "value",
      "value": "draft"
    },
    "updated_at": {
      "kind": "now"
    }
  },
  "storyboards": {
    "audio_meta": {
      "kind": "value",
      "value": {}
    },
    "brief": {
      "kind": "value",
      "value": {}
    },
    "created_at": {
      "kind": "now"
    },
    "id": {
      "kind": "uuid"
    },
    "status": {
      "kind": "value",
      "value": "draft"
    },
    "updated_at": {
      "kind": "now"
    },
    "version": {
      "kind": "value",
      "value": 1
    }
  },
  "take_assemblies": {
    "created_at": {
      "kind": "now"
    },
    "id": {
      "kind": "uuid"
    },
    "notes": {
      "kind": "value",
      "value": {}
    },
    "segments": {
      "kind": "value",
      "value": []
    },
    "source": {
      "kind": "value",
      "value": "manual"
    },
    "status": {
      "kind": "value",
      "value": "draft"
    },
    "updated_at": {
      "kind": "now"
    }
  },
  "take_reviews": {
    "created_at": {
      "kind": "now"
    },
    "id": {
      "kind": "uuid"
    },
    "issues": {
      "kind": "value",
      "value": []
    },
    "kind": {
      "kind": "value",
      "value": "take"
    },
    "scores": {
      "kind": "value",
      "value": {}
    }
  },
  "timelines": {
    "created_at": {
      "kind": "now"
    },
    "excluded_block_ids": {
      "kind": "value",
      "value": []
    },
    "fps": {
      "kind": "value",
      "value": 24
    },
    "height": {
      "kind": "value",
      "value": 720
    },
    "id": {
      "kind": "uuid"
    },
    "name": {
      "kind": "value",
      "value": "Main"
    },
    "placed_audio_asset_ids": {
      "kind": "value",
      "value": []
    },
    "render_stale": {
      "kind": "value",
      "value": true
    },
    "updated_at": {
      "kind": "now"
    },
    "width": {
      "kind": "value",
      "value": 1280
    }
  },
  "tracks": {
    "audio_fx": {
      "kind": "value",
      "value": []
    },
    "automation": {
      "kind": "value",
      "value": []
    },
    "gain_db": {
      "kind": "value",
      "value": 0
    },
    "id": {
      "kind": "uuid"
    },
    "locked": {
      "kind": "value",
      "value": false
    },
    "muted": {
      "kind": "value",
      "value": false
    },
    "solo": {
      "kind": "value",
      "value": false
    }
  },
  "voice_clones": {
    "created_at": {
      "kind": "now"
    },
    "id": {
      "kind": "uuid"
    },
    "meta": {
      "kind": "value",
      "value": {}
    },
    "status": {
      "kind": "value",
      "value": "pending"
    },
    "updated_at": {
      "kind": "now"
    }
  }
};

/** Tables carrying a `moddatetime(updated_at)` BEFORE UPDATE trigger. */
export const TOUCH_UPDATED_AT: readonly string[] = [
  "bible_entries",
  "chat_threads",
  "clips",
  "collections",
  "custom_workflows",
  "generation_blocks",
  "projects",
  "scenes",
  "storyboards",
  "take_assemblies",
  "timelines",
  "voice_clones"
];

/** table -> its primary key columns. Two link tables here have a COMPOSITE
 *  key and no `id` column at all, so nothing may assume one: a store that
 *  invents an id for them works until the row is pushed to a database that has
 *  no such column, and an upsert has no conflict target without this. */
export const PRIMARY_KEYS: Readonly<Record<string, readonly string[]>> = {
  "assets": [
    "id"
  ],
  "beats": [
    "id"
  ],
  "bible_assets": [
    "entry_id",
    "asset_id"
  ],
  "bible_entries": [
    "id"
  ],
  "bible_revisions": [
    "id"
  ],
  "block_takes": [
    "id"
  ],
  "chat_messages": [
    "id"
  ],
  "chat_threads": [
    "id"
  ],
  "clips": [
    "id"
  ],
  "collection_assets": [
    "collection_id",
    "asset_id"
  ],
  "collections": [
    "id"
  ],
  "cost_ledger": [
    "id"
  ],
  "custom_workflows": [
    "id"
  ],
  "episodes": [
    "id"
  ],
  "generation_blocks": [
    "id"
  ],
  "jobs": [
    "id"
  ],
  "projects": [
    "id"
  ],
  "rag_chunks": [
    "id"
  ],
  "rag_documents": [
    "id"
  ],
  "scenes": [
    "id"
  ],
  "storyboards": [
    "id"
  ],
  "take_assemblies": [
    "id"
  ],
  "take_reviews": [
    "id"
  ],
  "timelines": [
    "id"
  ],
  "tracks": [
    "id"
  ],
  "voice_clones": [
    "id"
  ]
};

/** table -> foreign keys, with the ON DELETE action the database would take. */
export const FOREIGN_KEYS: Readonly<Record<string, readonly {
  column: string; parent: string; onDelete: string;
}[]>> = {
  "assets": [
    {
      "column": "project_id",
      "parent": "projects",
      "onDelete": "set null"
    }
  ],
  "beats": [
    {
      "column": "scene_id",
      "parent": "scenes",
      "onDelete": "cascade"
    }
  ],
  "bible_assets": [
    {
      "column": "asset_id",
      "parent": "assets",
      "onDelete": "cascade"
    },
    {
      "column": "entry_id",
      "parent": "bible_entries",
      "onDelete": "cascade"
    }
  ],
  "bible_entries": [
    {
      "column": "project_id",
      "parent": "projects",
      "onDelete": "cascade"
    },
    {
      "column": "voice_ref_asset_id",
      "parent": "assets",
      "onDelete": "set null"
    }
  ],
  "bible_revisions": [
    {
      "column": "entry_id",
      "parent": "bible_entries",
      "onDelete": "cascade"
    }
  ],
  "block_takes": [
    {
      "column": "asset_id",
      "parent": "assets",
      "onDelete": "cascade"
    },
    {
      "column": "block_id",
      "parent": "generation_blocks",
      "onDelete": "cascade"
    }
  ],
  "chat_messages": [
    {
      "column": "thread_id",
      "parent": "chat_threads",
      "onDelete": "cascade"
    }
  ],
  "chat_threads": [
    {
      "column": "episode_id",
      "parent": "episodes",
      "onDelete": "set null"
    },
    {
      "column": "project_id",
      "parent": "projects",
      "onDelete": "cascade"
    }
  ],
  "clips": [
    {
      "column": "asset_id",
      "parent": "assets",
      "onDelete": "restrict"
    },
    {
      "column": "block_id",
      "parent": "generation_blocks",
      "onDelete": "set null"
    },
    {
      "column": "linked_clip_id",
      "parent": "clips",
      "onDelete": "set null"
    },
    {
      "column": "take_id",
      "parent": "block_takes",
      "onDelete": "set null"
    },
    {
      "column": "track_id",
      "parent": "tracks",
      "onDelete": "cascade"
    }
  ],
  "collection_assets": [
    {
      "column": "asset_id",
      "parent": "assets",
      "onDelete": "cascade"
    },
    {
      "column": "collection_id",
      "parent": "collections",
      "onDelete": "cascade"
    }
  ],
  "collections": [
    {
      "column": "project_id",
      "parent": "projects",
      "onDelete": "cascade"
    }
  ],
  "cost_ledger": [
    {
      "column": "project_id",
      "parent": "projects",
      "onDelete": "set null"
    }
  ],
  "custom_workflows": [
    {
      "column": "project_id",
      "parent": "projects",
      "onDelete": "cascade"
    }
  ],
  "episodes": [
    {
      "column": "project_id",
      "parent": "projects",
      "onDelete": "cascade"
    }
  ],
  "generation_blocks": [
    {
      "column": "active_take_id",
      "parent": "block_takes",
      "onDelete": "set null"
    },
    {
      "column": "chain_from_block_id",
      "parent": "generation_blocks",
      "onDelete": "set null"
    },
    {
      "column": "storyboard_id",
      "parent": "storyboards",
      "onDelete": "cascade"
    }
  ],
  "jobs": [
    {
      "column": "output_asset_id",
      "parent": "assets",
      "onDelete": "set null"
    },
    {
      "column": "project_id",
      "parent": "projects",
      "onDelete": "cascade"
    }
  ],
  "projects": [
    {
      "column": "cover_asset_id",
      "parent": "assets",
      "onDelete": "set null"
    }
  ],
  "rag_chunks": [
    {
      "column": "document_id",
      "parent": "rag_documents",
      "onDelete": "cascade"
    }
  ],
  "rag_documents": [
    {
      "column": "episode_id",
      "parent": "episodes",
      "onDelete": "set null"
    },
    {
      "column": "project_id",
      "parent": "projects",
      "onDelete": "cascade"
    }
  ],
  "scenes": [
    {
      "column": "environment_id",
      "parent": "bible_entries",
      "onDelete": "set null"
    },
    {
      "column": "still_asset_id",
      "parent": "assets",
      "onDelete": "set null"
    },
    {
      "column": "storyboard_id",
      "parent": "storyboards",
      "onDelete": "cascade"
    }
  ],
  "storyboards": [
    {
      "column": "audio_asset_id",
      "parent": "assets",
      "onDelete": "set null"
    },
    {
      "column": "episode_id",
      "parent": "episodes",
      "onDelete": "cascade"
    }
  ],
  "take_assemblies": [
    {
      "column": "block_id",
      "parent": "generation_blocks",
      "onDelete": "cascade"
    },
    {
      "column": "output_take_id",
      "parent": "block_takes",
      "onDelete": "set null"
    }
  ],
  "take_reviews": [
    {
      "column": "block_id",
      "parent": "generation_blocks",
      "onDelete": "cascade"
    },
    {
      "column": "storyboard_id",
      "parent": "storyboards",
      "onDelete": "cascade"
    },
    {
      "column": "take_id",
      "parent": "block_takes",
      "onDelete": "cascade"
    }
  ],
  "timelines": [
    {
      "column": "episode_id",
      "parent": "episodes",
      "onDelete": "cascade"
    },
    {
      "column": "render_asset_id",
      "parent": "assets",
      "onDelete": "set null"
    }
  ],
  "tracks": [
    {
      "column": "duck_under_track_id",
      "parent": "tracks",
      "onDelete": "set null"
    },
    {
      "column": "timeline_id",
      "parent": "timelines",
      "onDelete": "cascade"
    }
  ],
  "voice_clones": [
    {
      "column": "sample_asset_id",
      "parent": "assets",
      "onDelete": "set null"
    }
  ]
};

/** The ownership chain: child -> [parent table, local fk column, …], first hit
 *  wins. `set_row_owner` walks it to derive `owner_id`; the local store walks
 *  the same chain to derive `project_id`, which is what every share-scoped
 *  query filters on and what a local row would otherwise never carry. */
export const OWNERSHIP_PARENTS: Readonly<Record<string, readonly string[]>> = {
  "assets": [
    "projects",
    "project_id",
    "jobs",
    "source_job_id"
  ],
  "beats": [
    "scenes",
    "scene_id"
  ],
  "bible_assets": [
    "bible_entries",
    "entry_id"
  ],
  "bible_entries": [
    "projects",
    "project_id"
  ],
  "bible_revisions": [
    "bible_entries",
    "entry_id"
  ],
  "block_takes": [
    "generation_blocks",
    "block_id"
  ],
  "chat_messages": [
    "chat_threads",
    "thread_id"
  ],
  "chat_threads": [
    "projects",
    "project_id",
    "episodes",
    "episode_id"
  ],
  "clips": [
    "tracks",
    "track_id"
  ],
  "collection_assets": [
    "collections",
    "collection_id"
  ],
  "collections": [
    "projects",
    "project_id"
  ],
  "cost_ledger": [
    "projects",
    "project_id",
    "jobs",
    "job_id"
  ],
  "custom_workflows": [
    "projects",
    "project_id"
  ],
  "episodes": [
    "projects",
    "project_id"
  ],
  "generation_blocks": [
    "storyboards",
    "storyboard_id"
  ],
  "jobs": [
    "projects",
    "project_id",
    "episodes",
    "episode_id"
  ],
  "rag_chunks": [
    "rag_documents",
    "document_id"
  ],
  "rag_documents": [
    "projects",
    "project_id"
  ],
  "scenes": [
    "storyboards",
    "storyboard_id"
  ],
  "storyboards": [
    "episodes",
    "episode_id"
  ],
  "take_assemblies": [
    "generation_blocks",
    "block_id"
  ],
  "take_reviews": [
    "generation_blocks",
    "block_id",
    "storyboards",
    "storyboard_id"
  ],
  "timelines": [
    "episodes",
    "episode_id"
  ],
  "tracks": [
    "timelines",
    "timeline_id"
  ],
  "voice_clones": [
    "projects",
    "project_id"
  ]
};
