// GENERATED by scripts/gen_model_catalog.py — do not edit.
//
// Every model this build can offer, derived from infra/model_map.full.json
// (local rows) plus the hand-written hosted rows in the generator. Read it
// through src/lib/catalog.ts, never directly: that module is what the
// pickers, the frame grids and the studio plane all go through.
//
// Re-generate after ANY change to the model map or to the generator:
//   python3 scripts/gen_model_catalog.py
import type { ModelCatalogRow } from "./db/types";

const CATALOG: ModelCatalogRow[] = [
  {
    "id": "h3-local",
    "family": "minimax-h3",
    "display_name": "MiniMax H3 (local)",
    "kind": "video",
    "provider": "local",
    "modes": [
      "i2v",
      "t2v",
      "flf",
      "r2v"
    ],
    "sizes": [
      {
        "id": "480p",
        "label": "480p",
        "dims": {
          "16:9": [
            832,
            480
          ],
          "9:16": [
            480,
            832
          ],
          "1:1": [
            640,
            640
          ]
        }
      },
      {
        "id": "720p",
        "label": "720p",
        "dims": {
          "16:9": [
            1280,
            736
          ],
          "9:16": [
            736,
            1280
          ],
          "1:1": [
            960,
            960
          ]
        }
      },
      {
        "id": "1080p",
        "label": "1080p",
        "maxFrames": 81,
        "dims": {
          "16:9": [
            1920,
            1088
          ],
          "9:16": [
            1088,
            1920
          ],
          "1:1": [
            1440,
            1440
          ]
        }
      }
    ],
    "max_seconds": 15,
    "fps": 24,
    "frame_base": 17,
    "frame_rem": 5,
    "dim_step": 32,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "audio": true,
      "multiRef": 9,
      "refVideos": 3,
      "refAudios": 3,
      "flf": true,
      "videoEdit": true,
      "attribution": "MiniMax H3",
      "styleLoras": [
        {
          "key": "camera",
          "label": "Camera Motion",
          "strength": 0.9,
          "trigger": "camera motion",
          "hint": "Adds the moves H3 is weakest at. Strong: push-in / dolly in, pull-back / dolly out, handheld tracking. Good: orbit, aerial drone, crane / tilt, push-in-then-pull-back, macro. Weak: pan (sparse data — pair it with another move). Say the move in the shot prose ('slow push-in', 'dynamic handheld following the action'); the trigger is placed for you. Author: 0.8 gentle, 1.0 pronounced, above 1.2 the picture destabilises. Trained on fl2va (Comfy-Org build); r2v is outside the author's tests, as combat's was. Applied automatically to blocks whose camera lines move."
        },
        {
          "key": "combat",
          "label": "Combat Base V2",
          "hint": "Fight choreography, impact and stunt physics: strikes carry momentum when they miss, hit reactions persist and accumulate, and falls have real trajectories. Also lifts DIALOGUE scenes (author measures +19.5% in-shot motion, +34.2% audio RMS). It does NOT choreograph for you — say who strikes first, where it lands, how the other reacts and why the next move follows. Escalate by writing the tokens into the shot: none (steadiest anatomy) -> 'prfight2' (higher intensity) -> 'prfight2, prfin1' (heavy finisher). Those are V2's tokens — the lower half of the model page still describes V1 and names prfight1/prslow1, which this file was not trained on. In a shot with both, finish the action before the dialogue or motion reverts to the base model's slower feel. Author tested FL2VA only (i2v/t2v/flf), so r2v is out of distribution, and warns that HIGH weights cost H3's own fluidity — sped-up motion, blur, attacks that never recover. SAMPLER MATTERS MORE HERE THAN ANYWHERE ELSE: the author says to check it first when the LoRA looks muddy, and names res_multistep+simple or euler+beta. Plain MiniMax H3 already ships the first of those; every TURBO row replaces the sampler outright with the distillation's own at 6 steps, which is neither. On a turbo row this adapter has come back with ghosting; its motion and sharpness gains were measured on plain H3, not on turbo."
        }
      ],
      "maxLoras": 4,
      "refine": true,
      "splitPass": true,
      "latentUpscale": true
    },
    "local_files": {
      "vae": "minimax_h3_video_vae_fp16.safetensors",
      "audio_vae": "minimax_h3_audio_vae_fp32.safetensors",
      "text_encoders": [
        "qwen3vl_32b_minimax_h3_int8_convrot.safetensors"
      ],
      "fps": 24,
      "frame_base": 17,
      "frame_rem": 5,
      "lora_strength": 1.0,
      "style_loras": {
        "combat": "h3_combat_v2.safetensors",
        "camera": "camera_motion_h3_lora_v1_3000_pruned.safetensors"
      },
      "lora_defaults": {
        "camera": 0.9
      },
      "lora_triggers": {
        "camera": "camera motion"
      },
      "modes": {
        "i2v": {
          "workflow": "minimax_h3_i2v.json",
          "checkpoint": "minimax_h3_fl2va_int8_convrot.safetensors"
        },
        "t2v": {
          "workflow": "minimax_h3_t2v.json",
          "checkpoint": "minimax_h3_fl2va_int8_convrot.safetensors"
        },
        "flf": {
          "workflow": "minimax_h3_flf.json",
          "checkpoint": "minimax_h3_fl2va_int8_convrot.safetensors"
        },
        "r2v": {
          "workflow": "minimax_h3_r2v.json",
          "checkpoint": "minimax_h3_ref2va_int8_convrot.safetensors"
        }
      },
      "dim_step": 32,
      "refine": {
        "scale": 1.25,
        "steps": 4,
        "denoise": 0.2,
        "scheduler": "beta",
        "upscale_method": "lanczos",
        "freeze_audio": true
      },
      "split_pass": {
        "extend_steps": 3,
        "extend_from": 0.65,
        "extend_to": 0.28,
        "spacing": "sine",
        "split": 0.25,
        "lora_scale": 0.65,
        "turbo_scale": 0.29
      },
      "latent_upscale": {
        "model": "minimax_h3_latent_upscaler_3d_bf16.safetensors",
        "first_pass_mp": 0.35,
        "denoise": 0.45,
        "precision": "fp16"
      }
    },
    "enabled": true,
    "sort": 10
  },
  {
    "id": "h3-turbo-local",
    "family": "minimax-h3",
    "display_name": "MiniMax H3 · Turbo",
    "kind": "video",
    "provider": "local",
    "modes": [
      "i2v",
      "t2v",
      "flf",
      "r2v"
    ],
    "sizes": [
      {
        "id": "480p",
        "label": "480p",
        "dims": {
          "16:9": [
            832,
            480
          ],
          "9:16": [
            480,
            832
          ],
          "1:1": [
            640,
            640
          ]
        }
      },
      {
        "id": "720p",
        "label": "720p",
        "dims": {
          "16:9": [
            1280,
            736
          ],
          "9:16": [
            736,
            1280
          ],
          "1:1": [
            960,
            960
          ]
        }
      },
      {
        "id": "1080p",
        "label": "1080p",
        "maxFrames": 81,
        "dims": {
          "16:9": [
            1920,
            1088
          ],
          "9:16": [
            1088,
            1920
          ],
          "1:1": [
            1440,
            1440
          ]
        }
      }
    ],
    "max_seconds": 15,
    "fps": 24,
    "frame_base": 17,
    "frame_rem": 5,
    "dim_step": 32,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "audio": true,
      "multiRef": 9,
      "refVideos": 3,
      "refAudios": 3,
      "flf": true,
      "videoEdit": true,
      "attribution": "MiniMax H3",
      "turbo": true,
      "note": "Step-distilled: 6 steps instead of 20. Needs the MiniMaxH3TurboSampler node. Author's guidance is 6-8 steps; below 6 fast motion can smear.",
      "styleLoras": [
        {
          "key": "camera",
          "label": "Camera Motion",
          "strength": 0.9,
          "trigger": "camera motion",
          "hint": "Adds the moves H3 is weakest at. Strong: push-in / dolly in, pull-back / dolly out, handheld tracking. Good: orbit, aerial drone, crane / tilt, push-in-then-pull-back, macro. Weak: pan (sparse data — pair it with another move). Say the move in the shot prose ('slow push-in', 'dynamic handheld following the action'); the trigger is placed for you. Author: 0.8 gentle, 1.0 pronounced, above 1.2 the picture destabilises. Trained on fl2va (Comfy-Org build); r2v is outside the author's tests, as combat's was. Applied automatically to blocks whose camera lines move."
        },
        {
          "key": "combat",
          "label": "Combat Base V2",
          "hint": "Fight choreography, impact and stunt physics: strikes carry momentum when they miss, hit reactions persist and accumulate, and falls have real trajectories. Also lifts DIALOGUE scenes (author measures +19.5% in-shot motion, +34.2% audio RMS). It does NOT choreograph for you — say who strikes first, where it lands, how the other reacts and why the next move follows. Escalate by writing the tokens into the shot: none (steadiest anatomy) -> 'prfight2' (higher intensity) -> 'prfight2, prfin1' (heavy finisher). Those are V2's tokens — the lower half of the model page still describes V1 and names prfight1/prslow1, which this file was not trained on. In a shot with both, finish the action before the dialogue or motion reverts to the base model's slower feel. Author tested FL2VA only (i2v/t2v/flf), so r2v is out of distribution, and warns that HIGH weights cost H3's own fluidity — sped-up motion, blur, attacks that never recover. SAMPLER MATTERS MORE HERE THAN ANYWHERE ELSE: the author says to check it first when the LoRA looks muddy, and names res_multistep+simple or euler+beta. Plain MiniMax H3 already ships the first of those; every TURBO row replaces the sampler outright with the distillation's own at 6 steps, which is neither. On a turbo row this adapter has come back with ghosting; its motion and sharpness gains were measured on plain H3, not on turbo."
        }
      ],
      "maxLoras": 4,
      "refine": true,
      "splitPass": true,
      "latentUpscale": true
    },
    "local_files": {
      "vae": "minimax_h3_video_vae_fp16.safetensors",
      "audio_vae": "minimax_h3_audio_vae_fp32.safetensors",
      "text_encoders": [
        "qwen3vl_32b_minimax_h3_int8_convrot.safetensors"
      ],
      "fps": 24,
      "frame_base": 17,
      "frame_rem": 5,
      "turbo_lora": "minimax_h3_turbo_v4_step600_ema.safetensors",
      "turbo_strength": 1.0,
      "steps": 6,
      "lora_strength": 1.0,
      "style_loras": {
        "combat": "h3_combat_v2.safetensors",
        "camera": "camera_motion_h3_lora_v1_3000_pruned.safetensors"
      },
      "lora_defaults": {
        "camera": 0.9
      },
      "lora_triggers": {
        "camera": "camera motion"
      },
      "modes": {
        "i2v": {
          "workflow": "minimax_h3_i2v.json",
          "checkpoint": "minimax_h3_fl2va_int8_convrot.safetensors"
        },
        "t2v": {
          "workflow": "minimax_h3_t2v.json",
          "checkpoint": "minimax_h3_fl2va_int8_convrot.safetensors"
        },
        "flf": {
          "workflow": "minimax_h3_flf.json",
          "checkpoint": "minimax_h3_fl2va_int8_convrot.safetensors"
        },
        "r2v": {
          "workflow": "minimax_h3_r2v.json",
          "checkpoint": "minimax_h3_ref2va_int8_convrot.safetensors"
        }
      },
      "dim_step": 32,
      "refine": {
        "scale": 1.25,
        "steps": 4,
        "denoise": 0.2,
        "scheduler": "beta",
        "upscale_method": "lanczos",
        "freeze_audio": true
      },
      "split_pass": {
        "extend_steps": 3,
        "extend_from": 0.65,
        "extend_to": 0.28,
        "spacing": "sine",
        "split": 0.25,
        "lora_scale": 0.65,
        "turbo_scale": 0.29
      },
      "latent_upscale": {
        "model": "minimax_h3_latent_upscaler_3d_bf16.safetensors",
        "first_pass_mp": 0.35,
        "denoise": 0.45,
        "precision": "fp16"
      }
    },
    "enabled": true,
    "sort": 9
  },
  {
    "id": "h3-pdd-local",
    "family": "minimax-h3",
    "display_name": "MiniMax H3 · PDD 8-step",
    "kind": "video",
    "provider": "local",
    "modes": [
      "i2v",
      "t2v",
      "flf",
      "r2v"
    ],
    "sizes": [
      {
        "id": "480p",
        "label": "480p",
        "dims": {
          "16:9": [
            832,
            480
          ],
          "9:16": [
            480,
            832
          ],
          "1:1": [
            640,
            640
          ]
        }
      },
      {
        "id": "720p",
        "label": "720p",
        "dims": {
          "16:9": [
            1280,
            736
          ],
          "9:16": [
            736,
            1280
          ],
          "1:1": [
            960,
            960
          ]
        }
      },
      {
        "id": "1080p",
        "label": "1080p",
        "maxFrames": 81,
        "dims": {
          "16:9": [
            1920,
            1088
          ],
          "9:16": [
            1088,
            1920
          ],
          "1:1": [
            1440,
            1440
          ]
        }
      }
    ],
    "max_seconds": 15,
    "fps": 24,
    "frame_base": 17,
    "frame_rem": 5,
    "dim_step": 32,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "audio": true,
      "multiRef": 9,
      "refVideos": 3,
      "refAudios": 3,
      "flf": true,
      "videoEdit": true,
      "attribution": "MiniMax H3",
      "turbo": true,
      "note": "The official alibaba-pai 8-step distill. Turbo speed with cleaner frames side by side (no ghosting), and it has a reference-mode build, so episodes use it end to end. Sampler and schedule are fixed by the distill (euler, 8 steps).",
      "styleLoras": [
        {
          "key": "camera",
          "label": "Camera Motion",
          "strength": 0.9,
          "trigger": "camera motion",
          "hint": "Adds the moves H3 is weakest at. Strong: push-in / dolly in, pull-back / dolly out, handheld tracking. Good: orbit, aerial drone, crane / tilt, push-in-then-pull-back, macro. Weak: pan (sparse data — pair it with another move). Say the move in the shot prose ('slow push-in', 'dynamic handheld following the action'); the trigger is placed for you. Author: 0.8 gentle, 1.0 pronounced, above 1.2 the picture destabilises. Trained on fl2va (Comfy-Org build); r2v is outside the author's tests, as combat's was. Applied automatically to blocks whose camera lines move."
        },
        {
          "key": "combat",
          "label": "Combat Base V2",
          "hint": "Fight choreography, impact and stunt physics: strikes carry momentum when they miss, hit reactions persist and accumulate, and falls have real trajectories. Also lifts DIALOGUE scenes (author measures +19.5% in-shot motion, +34.2% audio RMS). It does NOT choreograph for you — say who strikes first, where it lands, how the other reacts and why the next move follows. Escalate by writing the tokens into the shot: none (steadiest anatomy) -> 'prfight2' (higher intensity) -> 'prfight2, prfin1' (heavy finisher). Those are V2's tokens — the lower half of the model page still describes V1 and names prfight1/prslow1, which this file was not trained on. In a shot with both, finish the action before the dialogue or motion reverts to the base model's slower feel. Author tested FL2VA only (i2v/t2v/flf), so r2v is out of distribution, and warns that HIGH weights cost H3's own fluidity — sped-up motion, blur, attacks that never recover. SAMPLER MATTERS MORE HERE THAN ANYWHERE ELSE: the author says to check it first when the LoRA looks muddy, and names res_multistep+simple or euler+beta. Plain MiniMax H3 already ships the first of those; every TURBO row replaces the sampler outright with the distillation's own at 6 steps, which is neither. On a turbo row this adapter has come back with ghosting; its motion and sharpness gains were measured on plain H3, not on turbo."
        }
      ],
      "maxLoras": 4,
      "latentUpscale": true
    },
    "local_files": {
      "vae": "minimax_h3_video_vae_fp16.safetensors",
      "audio_vae": "minimax_h3_audio_vae_fp32.safetensors",
      "text_encoders": [
        "qwen3vl_32b_minimax_h3_int8_convrot.safetensors"
      ],
      "fps": 24,
      "frame_base": 17,
      "frame_rem": 5,
      "lora_strength": 1.0,
      "style_loras": {
        "combat": "h3_combat_v2.safetensors",
        "camera": "camera_motion_h3_lora_v1_3000_pruned.safetensors"
      },
      "lora_defaults": {
        "camera": 0.9
      },
      "lora_triggers": {
        "camera": "camera motion"
      },
      "modes": {
        "i2v": {
          "workflow": "minimax_h3_i2v.json",
          "checkpoint": "minimax_h3_fl2va_int8_convrot.safetensors"
        },
        "t2v": {
          "workflow": "minimax_h3_t2v.json",
          "checkpoint": "minimax_h3_fl2va_int8_convrot.safetensors"
        },
        "flf": {
          "workflow": "minimax_h3_flf.json",
          "checkpoint": "minimax_h3_fl2va_int8_convrot.safetensors"
        },
        "r2v": {
          "workflow": "minimax_h3_r2v.json",
          "checkpoint": "minimax_h3_ref2va_int8_convrot.safetensors"
        }
      },
      "dim_step": 32,
      "pdd": {
        "fl2va": "MiniMax-H3-FL2VA-Acc-8Step.safetensors",
        "ref2va": "MiniMax-H3-Ref2VA-Acc-8Step.safetensors",
        "nfe": "8"
      },
      "extra_nodes": [
        "https://github.com/Jalen-Brunson/ComfyUI-MiniMax-H3-PDD-Acc"
      ],
      "steps": 8,
      "latent_upscale": {
        "model": "minimax_h3_latent_upscaler_3d_bf16.safetensors",
        "first_pass_mp": 0.35,
        "denoise": 0.45,
        "precision": "fp16"
      }
    },
    "enabled": true,
    "sort": 11
  },
  {
    "id": "h3-lightx2v-local",
    "family": "minimax-h3",
    "display_name": "MiniMax H3 · Turbo (lightx2v)",
    "kind": "video",
    "provider": "local",
    "modes": [
      "i2v",
      "t2v",
      "flf"
    ],
    "sizes": [
      {
        "id": "480p",
        "label": "480p",
        "dims": {
          "16:9": [
            832,
            480
          ],
          "9:16": [
            480,
            832
          ],
          "1:1": [
            640,
            640
          ]
        }
      },
      {
        "id": "720p",
        "label": "720p",
        "dims": {
          "16:9": [
            1280,
            736
          ],
          "9:16": [
            736,
            1280
          ],
          "1:1": [
            960,
            960
          ]
        }
      },
      {
        "id": "1080p",
        "label": "1080p",
        "maxFrames": 81,
        "dims": {
          "16:9": [
            1920,
            1088
          ],
          "9:16": [
            1088,
            1920
          ],
          "1:1": [
            1440,
            1440
          ]
        }
      }
    ],
    "max_seconds": 15,
    "fps": 24,
    "frame_base": 17,
    "frame_rem": 5,
    "dim_step": 32,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "audio": true,
      "flf": true,
      "videoEdit": true,
      "attribution": "MiniMax H3",
      "turbo": true,
      "styleLoras": [
        {
          "key": "camera",
          "label": "Camera Motion",
          "strength": 0.9,
          "trigger": "camera motion",
          "hint": "Adds the moves H3 is weakest at. Strong: push-in / dolly in, pull-back / dolly out, handheld tracking. Good: orbit, aerial drone, crane / tilt, push-in-then-pull-back, macro. Weak: pan (sparse data — pair it with another move). Say the move in the shot prose ('slow push-in', 'dynamic handheld following the action'); the trigger is placed for you. Author: 0.8 gentle, 1.0 pronounced, above 1.2 the picture destabilises. Trained on fl2va (Comfy-Org build); r2v is outside the author's tests, as combat's was. Applied automatically to blocks whose camera lines move."
        },
        {
          "key": "combat",
          "label": "Combat Base V2",
          "hint": "Fight choreography, impact and stunt physics: strikes carry momentum when they miss, hit reactions persist and accumulate, and falls have real trajectories. Also lifts DIALOGUE scenes (author measures +19.5% in-shot motion, +34.2% audio RMS). It does NOT choreograph for you — say who strikes first, where it lands, how the other reacts and why the next move follows. Escalate by writing the tokens into the shot: none (steadiest anatomy) -> 'prfight2' (higher intensity) -> 'prfight2, prfin1' (heavy finisher). Those are V2's tokens — the lower half of the model page still describes V1 and names prfight1/prslow1, which this file was not trained on. In a shot with both, finish the action before the dialogue or motion reverts to the base model's slower feel. Author tested FL2VA only (i2v/t2v/flf), so r2v is out of distribution, and warns that HIGH weights cost H3's own fluidity — sped-up motion, blur, attacks that never recover. SAMPLER MATTERS MORE HERE THAN ANYWHERE ELSE: the author says to check it first when the LoRA looks muddy, and names res_multistep+simple or euler+beta. Plain MiniMax H3 already ships the first of those; every TURBO row replaces the sampler outright with the distillation's own at 6 steps, which is neither. On a turbo row this adapter has come back with ghosting; its motion and sharpness gains were measured on plain H3, not on turbo."
        }
      ],
      "maxLoras": 4,
      "note": "Step-distilled to 4 (vendor: strength 0.75, sampler er_sde). Needs no custom node, unlike the other turbo row. fl2va only — no reference mode. The vendor notes ComfyUI and Diffusers differ here on AUDIO quality, so check the sound before trusting a dialogue block to it.",
      "refine": true,
      "splitPass": true,
      "latentUpscale": true
    },
    "local_files": {
      "vae": "minimax_h3_video_vae_fp16.safetensors",
      "audio_vae": "minimax_h3_audio_vae_fp32.safetensors",
      "text_encoders": [
        "qwen3vl_32b_minimax_h3_int8_convrot.safetensors"
      ],
      "fps": 24,
      "frame_base": 17,
      "frame_rem": 5,
      "turbo_lora": "minimax_h3_lightx2v_turbo_4step_v01.safetensors",
      "turbo_strength": 0.75,
      "turbo_apply": "plain",
      "steps": 4,
      "sampler": "er_sde",
      "lora_strength": 1.0,
      "style_loras": {
        "combat": "h3_combat_v2.safetensors",
        "camera": "camera_motion_h3_lora_v1_3000_pruned.safetensors"
      },
      "lora_defaults": {
        "camera": 0.9
      },
      "lora_triggers": {
        "camera": "camera motion"
      },
      "modes": {
        "i2v": {
          "workflow": "minimax_h3_i2v.json",
          "checkpoint": "minimax_h3_fl2va_int8_convrot.safetensors"
        },
        "t2v": {
          "workflow": "minimax_h3_t2v.json",
          "checkpoint": "minimax_h3_fl2va_int8_convrot.safetensors"
        },
        "flf": {
          "workflow": "minimax_h3_flf.json",
          "checkpoint": "minimax_h3_fl2va_int8_convrot.safetensors"
        }
      },
      "dim_step": 32,
      "refine": {
        "scale": 1.25,
        "steps": 4,
        "denoise": 0.2,
        "scheduler": "beta",
        "upscale_method": "lanczos",
        "freeze_audio": true
      },
      "split_pass": {
        "extend_steps": 3,
        "extend_from": 0.65,
        "extend_to": 0.28,
        "spacing": "sine",
        "split": 0.25,
        "lora_scale": 0.65,
        "turbo_scale": 0.29
      },
      "latent_upscale": {
        "model": "minimax_h3_latent_upscaler_3d_bf16.safetensors",
        "first_pass_mp": 0.35,
        "denoise": 0.45,
        "precision": "fp16"
      }
    },
    "enabled": true,
    "sort": 12
  },
  {
    "id": "wan22-local",
    "family": "wan2.2",
    "display_name": "Wan 2.2 14B",
    "kind": "video",
    "provider": "local",
    "modes": [
      "i2v",
      "flf"
    ],
    "sizes": [
      {
        "id": "480p",
        "label": "480p",
        "dims": {
          "16:9": [
            832,
            480
          ],
          "9:16": [
            480,
            832
          ],
          "1:1": [
            640,
            640
          ]
        }
      },
      {
        "id": "720p",
        "label": "720p",
        "dims": {
          "16:9": [
            1280,
            736
          ],
          "9:16": [
            736,
            1280
          ],
          "1:1": [
            960,
            960
          ]
        }
      }
    ],
    "max_seconds": 8,
    "fps": 16,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {},
    "local_files": {
      "vae": "wan_2.1_vae.safetensors",
      "text_encoders": [
        "umt5_xxl_fp16.safetensors"
      ],
      "modes": {
        "i2v": {
          "workflow": "wan22_14b_i2v_fp8.json",
          "high": "wan2.2_i2v_high_noise_14B_fp8_scaled.safetensors",
          "low": "wan2.2_i2v_low_noise_14B_fp8_scaled.safetensors"
        },
        "flf": {
          "workflow": "wan22_14b_flf.json",
          "high": "wan2.2_i2v_high_noise_14B_fp8_scaled.safetensors",
          "low": "wan2.2_i2v_low_noise_14B_fp8_scaled.safetensors"
        }
      }
    },
    "enabled": true,
    "sort": 30
  },
  {
    "id": "wan-shinkai-local",
    "family": "wan2.2",
    "display_name": "Wan Shinkai",
    "kind": "video",
    "provider": "local",
    "modes": [
      "i2v"
    ],
    "sizes": [
      {
        "id": "480p",
        "label": "480p",
        "dims": {
          "16:9": [
            832,
            480
          ],
          "9:16": [
            480,
            832
          ],
          "1:1": [
            640,
            640
          ]
        }
      }
    ],
    "max_seconds": 8,
    "fps": 16,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {},
    "local_files": {
      "vae": "wan_2.1_vae.safetensors",
      "text_encoders": [
        "umt5_xxl_fp16.safetensors"
      ],
      "style_lora": "547095-wan-sh1nka1-e140.safetensors",
      "style_strength": 0.9,
      "trigger": "sh1nka1 style",
      "modes": {
        "i2v": {
          "workflow": "wan22_14b_i2v_style.json",
          "high": "wan2.2_i2v_high_noise_14B_fp8_scaled.safetensors",
          "low": "wan2.2_i2v_low_noise_14B_fp8_scaled.safetensors"
        }
      }
    },
    "enabled": true,
    "sort": 31
  },
  {
    "id": "animegen-local",
    "family": "wan2.2",
    "display_name": "AnimeGen",
    "kind": "video",
    "provider": "local",
    "modes": [
      "i2v"
    ],
    "sizes": [
      {
        "id": "480p",
        "label": "480p",
        "dims": {
          "16:9": [
            832,
            480
          ],
          "9:16": [
            480,
            832
          ],
          "1:1": [
            640,
            640
          ]
        }
      }
    ],
    "max_seconds": 8,
    "fps": 16,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {},
    "local_files": {
      "vae": "wan_2.1_vae.safetensors",
      "text_encoders": [
        "umt5_xxl_fp16.safetensors"
      ],
      "modes": {
        "i2v": {
          "workflow": "wan22_14b_i2v_fp8.json",
          "high": "animegen_i2v_high_noise_bf16.safetensors",
          "low": "animegen_i2v_low_noise_bf16.safetensors"
        }
      }
    },
    "enabled": true,
    "sort": 32
  },
  {
    "id": "ltx-ttgl-local",
    "family": "ltx-2.3",
    "display_name": "LTX 2.3 · TTGL",
    "kind": "video",
    "provider": "local",
    "modes": [
      "i2v"
    ],
    "sizes": [
      {
        "id": "480p",
        "label": "480p",
        "dims": {
          "16:9": [
            832,
            480
          ],
          "9:16": [
            480,
            832
          ],
          "1:1": [
            640,
            640
          ]
        }
      },
      {
        "id": "720p",
        "label": "720p",
        "dims": {
          "16:9": [
            1280,
            736
          ],
          "9:16": [
            736,
            1280
          ],
          "1:1": [
            960,
            960
          ]
        }
      }
    ],
    "max_seconds": 10,
    "fps": 24,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {},
    "local_files": {
      "vae": "LTX23_video_vae_bf16.safetensors",
      "audio_vae": "LTX23_audio_vae_bf16.safetensors",
      "text_encoders": [
        "gemma_3_12B_it_fp8_scaled.safetensors",
        "ltx-2.3_text_projection_bf16.safetensors"
      ],
      "fps": 24,
      "lora": "ltx23_gurren_lagann.safetensors",
      "lora_strength": 1.0,
      "trigger": "TTGL",
      "modes": {
        "i2v": {
          "workflow": "ltx23_i2v.json",
          "checkpoint": "ltx-2.3-22b-distilled-1.1_transformer_only_fp8_scaled.safetensors"
        }
      }
    },
    "enabled": true,
    "sort": 40
  },
  {
    "id": "ltx-env-local",
    "family": "ltx-2.3",
    "display_name": "LTX 2.3 · Shinkai env",
    "kind": "video",
    "provider": "local",
    "modes": [
      "i2v"
    ],
    "sizes": [
      {
        "id": "480p",
        "label": "480p",
        "dims": {
          "16:9": [
            832,
            480
          ],
          "9:16": [
            480,
            832
          ],
          "1:1": [
            640,
            640
          ]
        }
      },
      {
        "id": "720p",
        "label": "720p",
        "dims": {
          "16:9": [
            1280,
            736
          ],
          "9:16": [
            736,
            1280
          ],
          "1:1": [
            960,
            960
          ]
        }
      }
    ],
    "max_seconds": 10,
    "fps": 24,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {},
    "local_files": {
      "vae": "LTX23_video_vae_bf16.safetensors",
      "audio_vae": "LTX23_audio_vae_bf16.safetensors",
      "text_encoders": [
        "gemma_3_12B_it_fp8_scaled.safetensors",
        "ltx-2.3_text_projection_bf16.safetensors"
      ],
      "fps": 24,
      "lora": "ltx23_shinkai_env.safetensors",
      "lora_strength": 1.0,
      "trigger": "ANIMSTY, SHW_YN.",
      "modes": {
        "i2v": {
          "workflow": "ltx23_i2v.json",
          "checkpoint": "ltx-2.3-22b-distilled-1.1_transformer_only_fp8_scaled.safetensors"
        }
      }
    },
    "enabled": true,
    "sort": 41
  },
  {
    "id": "ltx-25-local",
    "family": "ltx-2.5",
    "display_name": "LTX 2.5 · native audio",
    "kind": "video",
    "provider": "local",
    "modes": [
      "t2v",
      "r2v"
    ],
    "sizes": [
      {
        "id": "480p",
        "label": "480p",
        "dims": {
          "16:9": [
            832,
            480
          ],
          "9:16": [
            480,
            832
          ],
          "1:1": [
            640,
            640
          ]
        }
      },
      {
        "id": "720p",
        "label": "720p",
        "dims": {
          "16:9": [
            1280,
            736
          ],
          "9:16": [
            736,
            1280
          ],
          "1:1": [
            960,
            960
          ]
        }
      }
    ],
    "max_seconds": 10,
    "fps": 24,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "audio": true,
      "multiRef": 4,
      "backgroundRef": true,
      "note": "22B distilled int8-convrot, audio generated natively. r2v stages up to 4 subject refs plus a dedicated background slot (Licon MSR)."
    },
    "local_files": {
      "vae": "ltx-2.5-video-vae-conv-bf16.safetensors",
      "audio_vae": "ltx-2.5-audio-vae-bf16.safetensors",
      "text_encoders": [
        "gemma4-12b-with-proj-ltx-2.5-comfy-int8-convrot.safetensors"
      ],
      "fps": 24,
      "frame_base": 8,
      "frame_rem": 1,
      "dim_step": 64,
      "latent_scale": 0.5,
      "latent_upscaler": "ltx-2.5-latent-spatial-upscaler-x2-bf16-1.0.safetensors",
      "msr_lora": "LTX-2.5-Licon-MSR-V1.safetensors",
      "extra_nodes": [
        "https://github.com/liconstudio/ComfyUI-LTX2.5-MSR"
      ],
      "modes": {
        "t2v": {
          "workflow": "ltx25_t2v.json",
          "checkpoint": "ltx-2.5-22b-distilled-transformer-comfy-int8-convrot.safetensors"
        },
        "i2v": {
          "workflow": "ltx25_i2v.json",
          "checkpoint": "ltx-2.5-22b-distilled-transformer-comfy-int8-convrot.safetensors"
        },
        "flf": {
          "workflow": "ltx25_flf.json",
          "checkpoint": "ltx-2.5-22b-distilled-transformer-comfy-int8-convrot.safetensors"
        },
        "r2v": {
          "workflow": "ltx25_r2v.json",
          "checkpoint": "ltx-2.5-22b-distilled-transformer-comfy-int8-convrot.safetensors"
        }
      }
    },
    "enabled": true,
    "sort": 42
  },
  {
    "id": "h3-api-768p",
    "family": "minimax-h3",
    "display_name": "MiniMax H3 API · 768p",
    "kind": "video",
    "provider": "minimax",
    "modes": [
      "t2v",
      "i2v",
      "flf",
      "r2v"
    ],
    "sizes": null,
    "max_seconds": 15,
    "fps": 24,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "second",
      "usd": 0.09,
      "estimate": true,
      "note": "official beta price; some sources list $0.08/s; first 5 image refs free then $0.04 ea"
    },
    "capabilities": {
      "audio": true,
      "multiRef": 9,
      "refVideos": 3,
      "flf": true,
      "attribution": "MiniMax H3",
      "adapter": "minimax_api",
      "blocked": "the studio has no key for this provider yet — add your own under API keys"
    },
    "local_files": {
      "adapter": "minimax_api",
      "api_model": "MiniMax-H3"
    },
    "enabled": false,
    "sort": 20
  },
  {
    "id": "h3-api-2k",
    "family": "minimax-h3",
    "display_name": "MiniMax H3 API · 2K",
    "kind": "video",
    "provider": "minimax",
    "modes": [
      "t2v",
      "i2v",
      "flf",
      "r2v"
    ],
    "sizes": null,
    "max_seconds": 15,
    "fps": 24,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "second",
      "usd": 0.13,
      "note": "official 2K price; ~$1.95 per 15s master"
    },
    "capabilities": {
      "audio": true,
      "multiRef": 9,
      "refVideos": 3,
      "flf": true,
      "attribution": "MiniMax H3",
      "adapter": "minimax_api",
      "blocked": "the studio has no key for this provider yet — add your own under API keys"
    },
    "local_files": {
      "adapter": "minimax_api",
      "api_model": "MiniMax-H3"
    },
    "enabled": false,
    "sort": 21
  },
  {
    "id": "h3-api-regen2k",
    "family": "minimax-h3",
    "display_name": "H3 Regenerate-2K (mastering)",
    "kind": "video",
    "provider": "minimax",
    "modes": [
      "v2v"
    ],
    "sizes": null,
    "max_seconds": 15,
    "fps": 24,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "second",
      "usd": 0.05,
      "estimate": true,
      "note": "in-context 2K regeneration of an H3 output; one source lists $0.10/s"
    },
    "capabilities": {
      "attribution": "MiniMax H3",
      "adapter": "minimax_api",
      "blocked": "video-to-video is not wired on either plane yet"
    },
    "local_files": null,
    "enabled": false,
    "sort": 22
  },
  {
    "id": "fal-h3-2k",
    "family": "minimax-h3",
    "display_name": "MiniMax H3 via fal · 2K",
    "kind": "video",
    "provider": "fal",
    "modes": [
      "t2v",
      "i2v",
      "r2v"
    ],
    "sizes": null,
    "max_seconds": 15,
    "fps": 24,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "second",
      "usd": 0.26,
      "estimate": true,
      "note": "$3.90 per 15s — official API is cheaper"
    },
    "capabilities": {
      "audio": true,
      "multiRef": 9,
      "refVideos": 3,
      "flf": false,
      "attribution": "MiniMax H3",
      "adapter": "fal_video",
      "blocked": "the studio has no key for this provider yet — add your own under API keys"
    },
    "local_files": {
      "adapter": "fal_video",
      "fal": {
        "endpoints": {
          "t2v": "fal-ai/minimax/hailuo-3",
          "i2v": "fal-ai/minimax/hailuo-3",
          "r2v": "fal-ai/minimax/hailuo-3"
        },
        "duration": "int",
        "aspect": false,
        "start": "image_url",
        "images": "reference_image_urls",
        "max_refs": 9
      }
    },
    "enabled": false,
    "sort": 23
  },
  {
    "id": "seedance-2.5",
    "family": "seedance",
    "display_name": "Seedance 2.5",
    "kind": "video",
    "provider": "fal",
    "modes": [
      "t2v",
      "i2v",
      "flf",
      "r2v"
    ],
    "sizes": null,
    "max_seconds": 30,
    "fps": 24,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "second",
      "usd": 0.05,
      "estimate": true,
      "note": "fal does not publish a flat per-second figure for 2.5 — unverified, and only the ledger reads it"
    },
    "capabilities": {
      "audio": true,
      "multiRef": 50,
      "refVideos": 50,
      "refAudios": 50,
      "flf": true,
      "adapter": "fal_video",
      "note": "30s in one pass, up to 50 mixed image/video/audio references. The prompt addresses them by position — [Image1], [Video1], [Audio1] — so reference ORDER is part of the instruction, not a detail.",
      "blocked": "the studio has no key for this provider yet — add your own under API keys"
    },
    "local_files": {
      "adapter": "fal_video",
      "fal": {
        "endpoints": {
          "t2v": "bytedance/seedance-2.5/text-to-video",
          "i2v": {
            "id": "bytedance/seedance-2.5/image-to-video",
            "images": null,
            "videos": null,
            "audios": null
          },
          "flf": {
            "id": "bytedance/seedance-2.5/image-to-video",
            "images": null,
            "videos": null,
            "audios": null
          },
          "r2v": "bytedance/seedance-2.5/reference-to-video"
        },
        "duration": "string",
        "durations": [
          "auto",
          "4",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20",
          "21",
          "22",
          "23",
          "24",
          "25",
          "26",
          "27",
          "28",
          "29",
          "30"
        ],
        "resolutions": [
          "480p",
          "720p"
        ],
        "aspect": true,
        "audio_flag": "generate_audio",
        "start": "image_url",
        "end": "end_image_url",
        "images": "image_urls",
        "videos": "video_urls",
        "audios": "audio_urls",
        "max_refs": 50
      }
    },
    "enabled": false,
    "sort": 24
  },
  {
    "id": "seedance-2-fast",
    "family": "seedance",
    "display_name": "Seedance 2.0 Fast",
    "kind": "video",
    "provider": "fal",
    "modes": [
      "t2v",
      "i2v"
    ],
    "sizes": null,
    "max_seconds": 8,
    "fps": 24,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "second",
      "usd": 0.022,
      "estimate": true,
      "note": "1080p, no audio"
    },
    "capabilities": {
      "adapter": "fal_video",
      "blocked": "the studio has no key for this provider yet — add your own under API keys"
    },
    "local_files": {
      "adapter": "fal_video",
      "fal": {
        "endpoints": {
          "t2v": "bytedance/seedance-2.0/text-to-video",
          "i2v": "bytedance/seedance-2.0/image-to-video"
        },
        "duration": "string",
        "resolutions": [
          "480p",
          "720p",
          "1080p"
        ],
        "aspect": true,
        "start": "image_url",
        "max_refs": 4
      }
    },
    "enabled": false,
    "sort": 60
  },
  {
    "id": "wan3-video",
    "family": "wan3",
    "display_name": "Wan 3.0",
    "kind": "video",
    "provider": "alibaba",
    "modes": [
      "t2v",
      "i2v",
      "flf",
      "r2v"
    ],
    "sizes": null,
    "max_seconds": 30,
    "fps": 24,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "second",
      "usd": 0.1,
      "note": "published API pricing: $0.05/s 480P, $0.10/s 720P, $0.20/s 1080P — wan_api books the tier it rendered"
    },
    "capabilities": {
      "audio": true,
      "multiRef": 10,
      "refVideos": 5,
      "refAudios": 5,
      "flf": true,
      "adapter": "wan_api",
      "note": "first frame, last frame, and mixed image/video/audio references on one endpoint — the only hosted row that can do a chain, an extend and a reference shot.",
      "blocked": "the studio has no key for this provider yet — add your own under API keys"
    },
    "local_files": {
      "adapter": "wan_api",
      "api_model": "wan3.0-video"
    },
    "enabled": false,
    "sort": 25
  },
  {
    "id": "wan3-video-prime",
    "family": "wan3",
    "display_name": "Wan 3.0 Prime (fast)",
    "kind": "video",
    "provider": "alibaba",
    "modes": [
      "t2v",
      "i2v",
      "flf",
      "r2v"
    ],
    "sizes": null,
    "max_seconds": 30,
    "fps": 24,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "second",
      "usd": 0.1,
      "estimate": true,
      "note": "the high-speed build; Alibaba does not publish a separate rate, so this mirrors the standard one"
    },
    "capabilities": {
      "audio": true,
      "multiRef": 10,
      "refVideos": 5,
      "refAudios": 5,
      "flf": true,
      "adapter": "wan_api",
      "note": "first frame, last frame, and mixed image/video/audio references on one endpoint — the only hosted row that can do a chain, an extend and a reference shot.",
      "blocked": "the studio has no key for this provider yet — add your own under API keys"
    },
    "local_files": {
      "adapter": "wan_api",
      "api_model": "wan3.0-video-prime"
    },
    "enabled": false,
    "sort": 26
  },
  {
    "id": "flux-3-video",
    "family": "flux3",
    "display_name": "FLUX 3 Video",
    "kind": "video",
    "provider": "fal",
    "modes": [
      "t2v"
    ],
    "sizes": null,
    "max_seconds": 20,
    "fps": 24,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "second",
      "usd": 0.08,
      "estimate": true,
      "note": "fal does not publish a flat per-second figure — unverified"
    },
    "capabilities": {
      "audio": true,
      "adapter": "fal_video",
      "note": "20s with native audio. Only text-to-video is documented on fal; BFL's own API adds image-to-video and video continuation on one endpoint.",
      "blocked": "the studio has no key for this provider yet — add your own under API keys"
    },
    "local_files": {
      "adapter": "fal_video",
      "fal": {
        "endpoints": {
          "t2v": "blackforestlabs/flux-3/text-to-video"
        },
        "duration": "string",
        "durations": [
          "auto",
          "5",
          "6",
          "7",
          "8",
          "9",
          "10",
          "11",
          "12",
          "13",
          "14",
          "15",
          "16",
          "17",
          "18",
          "19",
          "20"
        ],
        "resolutions": [
          "720p",
          "1080p"
        ],
        "aspect": true,
        "audio_flag": "generate_audio"
      }
    },
    "enabled": false,
    "sort": 27
  },
  {
    "id": "gemini-omni-flash",
    "family": "gemini-omni",
    "display_name": "Gemini Omni Flash",
    "kind": "video",
    "provider": "google",
    "modes": [
      "t2v",
      "i2v",
      "r2v"
    ],
    "sizes": null,
    "max_seconds": 10,
    "fps": 24,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "second",
      "usd": 0.1,
      "note": "published preview price"
    },
    "capabilities": {
      "audio": true,
      "multiRef": 7,
      "refVideos": 3,
      "flf": false,
      "adapter": "gemini_video",
      "note": "7 reference images + 3 short clips, native audio. No first-and-last-frame mode, so it cannot serve a chain — the closing frame would only be described.",
      "blocked": "not verified against the live API yet — see providers/gemini_video.py"
    },
    "local_files": {
      "adapter": "gemini_video",
      "model": "gemini-omni-1.1-flash"
    },
    "enabled": false,
    "sort": 28
  },
  {
    "id": "klein-local",
    "family": "flux2",
    "display_name": "Flux 2 Klein 9B",
    "kind": "image",
    "provider": "local",
    "modes": [
      "t2i",
      "r2i",
      "edit"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "multiRef": 6,
      "refs": 6,
      "edit": true,
      "maxLoras": 3,
      "styleLoras": [
        {
          "key": "shinkai",
          "label": "Shinkai",
          "trigger": "anime screencap",
          "hint": "Anime-screencap look, Klein 9B build. Was forced on every Klein render before; now opt-in."
        }
      ]
    },
    "local_files": {
      "family": "klein",
      "unet": "FLUX1/flux-2-klein-base-9b.safetensors",
      "text_encoder": "qwen_3_8b_fp8mixed.safetensors",
      "vae": "flux2-vae.safetensors",
      "steps": 50,
      "cfg": 4.0,
      "style_loras": {
        "shinkai": "flux2_klein_shinkai_v3.safetensors"
      },
      "lora_triggers": {
        "shinkai": "anime screencap"
      }
    },
    "enabled": true,
    "sort": 55
  },
  {
    "id": "flux2-klein-4b-local",
    "family": "flux2",
    "display_name": "Flux 2 Klein 4B",
    "kind": "image",
    "provider": "local",
    "modes": [
      "t2i",
      "r2i"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "refs": 4,
      "multiRef": 4,
      "note": "4 steps, Apache 2.0, ~4GB of weights — the reference model a laptop can hold"
    },
    "local_files": {
      "family": "flux2",
      "unet": "flux-2-klein-4b-fp8.safetensors",
      "text_encoder": "qwen_3_4b_fp4_flux2.safetensors",
      "vae": "flux2-vae.safetensors",
      "steps": 4,
      "max_refs": 4
    },
    "enabled": true,
    "sort": 58
  },
  {
    "id": "krea2-local",
    "family": "krea2",
    "display_name": "Krea 2 Turbo",
    "kind": "image",
    "provider": "local",
    "modes": [
      "t2i",
      "r2i",
      "edit"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "styleLoras": [
        {
          "key": "lenovo",
          "label": "UltraReal",
          "strength": 1.2,
          "hint": "Photographic realism. No trigger word. Author's range: 0.8 on a raw checkpoint, 1.2-2.0 on turbo (these are turbo)."
        },
        {
          "key": "identity",
          "label": "Identity Edit",
          "hint": "Identity-preserving instruction edits (v1.2): restage or redress a person while keeping the face. The outfit-variant path uses it automatically; strength 1.0, turbo 8-12 steps."
        },
        {
          "key": "realism",
          "label": "Realism Engine",
          "hint": "v3.1, 1.5GB — broad concept knowledge and photographic realism. No trigger word."
        }
      ],
      "multiRef": 4,
      "refs": 4,
      "edit": true,
      "maxLoras": 5,
      "refNode": "Krea2EditRebalance",
      "identityEdit": true
    },
    "local_files": {
      "family": "krea2",
      "unet": "Krea2/krea2_turbo_fp8_scaled.safetensors",
      "text_encoder": "Qwen3VL4B/qwen3vl_4b_bf16.safetensors",
      "vae": "qwen_image_vae.safetensors",
      "steps": 8,
      "cfg": 1.0,
      "sampler": "euler",
      "scheduler": "simple",
      "lora_strength": 1.0,
      "style_loras": {
        "lenovo": "krea2_lenovo_ultrareal_v1.safetensors",
        "identity": "krea2_identity_edit_v1_2.safetensors",
        "realism": "krea2_realism_engine_v3.1.safetensors"
      },
      "identity_edit": {
        "lora": "identity",
        "ref_boost": 3.0,
        "grounding_px": 768,
        "scene_boost": 1.0
      }
    },
    "enabled": true,
    "sort": 50
  },
  {
    "id": "qwen-edit-local",
    "family": "qwen",
    "display_name": "Qwen-Image-Edit 2511",
    "kind": "image",
    "provider": "local",
    "modes": [
      "t2i",
      "r2i",
      "edit"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "refs": 3,
      "multiRef": 3,
      "edit": true,
      "note": "reference-driven editing; strong text rendering"
    },
    "local_files": {
      "family": "qwen",
      "unet": "qwen_image_edit_2511_fp8mixed.safetensors",
      "text_encoder": "qwen_2.5_vl_7b_fp8_scaled.safetensors",
      "vae": "qwen_image_vae.safetensors",
      "steps": 20,
      "cfg": 2.5,
      "shift": 3.1,
      "sampler": "euler",
      "scheduler": "simple",
      "lora_strength": 1.0
    },
    "enabled": true,
    "sort": 49
  },
  {
    "id": "sensenova-u1-local",
    "family": "sensenova",
    "display_name": "SenseNova U1.5 8B",
    "kind": "image",
    "provider": "local",
    "modes": [
      "t2i",
      "r2i",
      "edit"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "refs": 10,
      "multiRef": 10,
      "edit": true,
      "note": "unified multimodal model — obeys written camera direction over a staged plate, holds a closed cast, renders legible text; generates natively at ~4MP, so a smaller request is snapped up and downscaled"
    },
    "local_files": {
      "family": "sensenova",
      "model_path": "/data/models/sensenova/SenseNova-U1.5-8B-MoT",
      "steps": 50,
      "cfg": 4.0,
      "img_cfg": 1.0,
      "timestep_shift": 3.0,
      "cfg_norm": "none",
      "dtype": "bfloat16",
      "attn_backend": "auto",
      "vram_mode": "full",
      "max_refs": 10
    },
    "enabled": true,
    "sort": 48
  },
  {
    "id": "hikari-anima-local",
    "family": "anima",
    "display_name": "Hikari Anima 1.0",
    "kind": "image",
    "provider": "local",
    "modes": [
      "t2i"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "noEdit": true,
      "negativePrompt": true,
      "maxLoras": 3,
      "defaultNegative": "worst quality, low quality, blurry, jpeg artifacts, sepia"
    },
    "local_files": {
      "family": "anima",
      "unet": "Anima/hikariAnima_100.safetensors",
      "text_encoder": "qwen_3_06b_base.safetensors",
      "clip_type": "stable_diffusion",
      "vae": "qwen_image_vae.safetensors",
      "steps": 30,
      "cfg": 4.0,
      "sampler": "euler",
      "scheduler": "simple",
      "lora_strength": 1.0,
      "negative": "worst quality, low quality, blurry, jpeg artifacts, sepia"
    },
    "enabled": true,
    "sort": 56
  },
  {
    "id": "anima-29b-local",
    "family": "anima",
    "display_name": "Anima 2.9B",
    "kind": "image",
    "provider": "local",
    "modes": [
      "t2i"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "noEdit": true,
      "negativePrompt": true,
      "maxLoras": 3,
      "defaultNegative": "worst quality, low quality, blurry, jpeg artifacts, sepia",
      "note": "Anime illustration, danbooru/gelbooru tags plus @artist tags and year tags; name a character WITH its series or the model confuses it. Knowledge cutoff July 2026. Quality/score tags are optional — not trained on. THE MORE DETAILED THE PROMPT THE BETTER: a short prompt gets a bland empty background. 32 steps at cfg 4.0 here; the author's band is 28-50 steps at cfg 3.5-5 and calls 50 the highest quality. Non-commercial licence."
    },
    "local_files": {
      "family": "anima",
      "unet": "Anima/anima_29b_preview_v1.safetensors",
      "text_encoder": "qwen_3_06b_base.safetensors",
      "clip_type": "stable_diffusion",
      "vae": "qwen_image_vae.safetensors",
      "steps": 32,
      "cfg": 4.0,
      "sampler": "euler",
      "scheduler": "sgm_uniform",
      "lora_strength": 1.0,
      "negative": "worst quality, low quality, blurry, jpeg artifacts, sepia"
    },
    "enabled": true,
    "sort": 57
  },
  {
    "id": "h3-image-local",
    "family": "minimax-h3",
    "display_name": "MiniMax H3 · image",
    "kind": "image",
    "provider": "local",
    "modes": [
      "t2i",
      "r2i",
      "edit"
    ],
    "sizes": [
      {
        "id": "1mp",
        "label": "1MP",
        "dims": {
          "16:9": [
            1280,
            736
          ],
          "9:16": [
            736,
            1280
          ],
          "1:1": [
            1024,
            1024
          ]
        }
      },
      {
        "id": "2mp",
        "label": "2MP",
        "dims": {
          "16:9": [
            1920,
            1088
          ],
          "9:16": [
            1088,
            1920
          ],
          "1:1": [
            1376,
            1376
          ]
        }
      }
    ],
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "refs": 9,
      "multiRef": 9,
      "edit": true,
      "maxLoras": 2,
      "attribution": "MiniMax H3",
      "styleLoras": [
        {
          "key": "thisisfine",
          "label": "ThisIsFine (detail)",
          "hint": "Detail/texture lift for the REFERENCE path — trained on ref2va (the checkpoint a job with references runs on). No trigger. On plain text-to-image, which runs fl2va, it is out of distribution: expect less from it there."
        }
      ],
      "note": "one frame of the video model; nine reference images — more than any other local model. 20 steps, so it is the slow one; the turbo row is the same model at 4-8 steps."
    },
    "local_files": {
      "family": "h3",
      "from_model": "minimax-h3",
      "mode": "r2v",
      "steps": 20,
      "image_vae": "minimax_h3_t1_image_vae_step1597.safetensors",
      "lora_strength": 1.0,
      "style_loras": {
        "thisisfine": "h3_thisisfine_r2v_v01.safetensors"
      }
    },
    "enabled": true,
    "sort": 52
  },
  {
    "id": "h3-image-turbo-local",
    "family": "minimax-h3",
    "display_name": "MiniMax H3 · image (turbo)",
    "kind": "image",
    "provider": "local",
    "modes": [
      "t2i",
      "r2i",
      "edit"
    ],
    "sizes": [
      {
        "id": "1mp",
        "label": "1MP",
        "dims": {
          "16:9": [
            1280,
            736
          ],
          "9:16": [
            736,
            1280
          ],
          "1:1": [
            1024,
            1024
          ]
        }
      },
      {
        "id": "2mp",
        "label": "2MP",
        "dims": {
          "16:9": [
            1920,
            1088
          ],
          "9:16": [
            1088,
            1920
          ],
          "1:1": [
            1376,
            1376
          ]
        }
      }
    ],
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "refs": 9,
      "multiRef": 9,
      "edit": true,
      "maxLoras": 2,
      "attribution": "MiniMax H3",
      "styleLoras": [
        {
          "key": "thisisfine",
          "label": "ThisIsFine (detail)",
          "hint": "Detail/texture lift for the REFERENCE path — trained on ref2va (the checkpoint a job with references runs on). No trigger. On plain text-to-image, which runs fl2va, it is out of distribution: expect less from it there."
        }
      ],
      "note": "lightx2v step distillation: 8 steps for text-to-image and single-image edits, 4 for the reference path. Try this first; fall back to the plain row if a render comes out flat."
    },
    "local_files": {
      "family": "h3",
      "from_model": "minimax-h3",
      "mode": "r2v",
      "image_vae": "minimax_h3_t1_image_vae_step1597.safetensors",
      "scheduler": "simple",
      "frame_turbo": {
        "lora": "minimax_h3_lightx2v_turbo_8step_v10.safetensors",
        "steps": 8,
        "strength": 1.0,
        "sampler": "sa_solver"
      },
      "ref_turbo": {
        "lora": "minimax_h3_lightx2v_ref2v_turbo_4step_v01.safetensors",
        "steps": 4,
        "strength": 0.75,
        "sampler": "er_sde"
      },
      "lora_strength": 1.0,
      "style_loras": {
        "thisisfine": "h3_thisisfine_r2v_v01.safetensors"
      }
    },
    "enabled": true,
    "sort": 53
  },
  {
    "id": "h3-image-pdd-local",
    "family": "minimax-h3",
    "display_name": "MiniMax H3 · image (PDD)",
    "kind": "image",
    "provider": "local",
    "modes": [
      "t2i",
      "r2i",
      "edit"
    ],
    "sizes": [
      {
        "id": "1mp",
        "label": "1MP",
        "dims": {
          "16:9": [
            1280,
            736
          ],
          "9:16": [
            736,
            1280
          ],
          "1:1": [
            1024,
            1024
          ]
        }
      },
      {
        "id": "2mp",
        "label": "2MP",
        "dims": {
          "16:9": [
            1920,
            1088
          ],
          "9:16": [
            1088,
            1920
          ],
          "1:1": [
            1376,
            1376
          ]
        }
      }
    ],
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "refs": 9,
      "multiRef": 9,
      "edit": true,
      "maxLoras": 2,
      "attribution": "MiniMax H3",
      "styleLoras": [
        {
          "key": "thisisfine",
          "label": "ThisIsFine (detail)",
          "hint": "Detail/texture lift for the REFERENCE path — trained on ref2va (the checkpoint a job with references runs on). No trigger. On plain text-to-image, which runs fl2va, it is out of distribution: expect less from it there."
        }
      ],
      "note": "the official 8-step distillation, and the one that applies to our pruned weights without dropping its adaln modules. Same 8 steps whichever path a job takes, unlike the turbo row's 8/4 split. Only 4, 6 or 8 are legal — the step count is the trained grid, not a quality dial."
    },
    "local_files": {
      "family": "h3",
      "from_model": "minimax-h3-pdd",
      "mode": "r2v",
      "image_vae": "minimax_h3_t1_image_vae_step1597.safetensors",
      "scheduler": "simple",
      "steps": 8,
      "lora_strength": 1.0,
      "style_loras": {
        "thisisfine": "h3_thisisfine_r2v_v01.safetensors"
      }
    },
    "enabled": true,
    "sort": 54
  },
  {
    "id": "gpt-image-1.5",
    "family": "openai",
    "display_name": "GPT Image 1.5",
    "kind": "image",
    "provider": "openai",
    "modes": [
      "t2i",
      "edit"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "image",
      "usd": 0.07,
      "estimate": true,
      "note": "quality-dependent; multi-image edit blends references"
    },
    "capabilities": {
      "multiRef": 10,
      "edit": true
    },
    "local_files": {
      "model": "gpt-image-1.5"
    },
    "enabled": true,
    "sort": 60
  },
  {
    "id": "gpt-image-2",
    "family": "openai",
    "display_name": "GPT Image 2",
    "kind": "image",
    "provider": "openai",
    "modes": [
      "t2i",
      "edit"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "image",
      "usd": 0.06,
      "estimate": true,
      "note": "billed on tokens: ~$0.055 for a 1536x1024 two-image edit"
    },
    "capabilities": {
      "multiRef": 8,
      "edit": true,
      "note": "keeps the source plate; the local edit models cannot"
    },
    "local_files": {
      "model": "gpt-image-2"
    },
    "enabled": true,
    "sort": 59
  },
  {
    "id": "nano-banana-2",
    "family": "gemini",
    "display_name": "Nano Banana 2",
    "kind": "image",
    "provider": "google",
    "modes": [
      "t2i",
      "edit"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "image",
      "usd": 0.067,
      "estimate": true,
      "text_in": 0.3,
      "image_out": 60.0,
      "note": "$0.067 at 1K, $0.101 at 2K; batch is half"
    },
    "capabilities": {
      "multiRef": 14,
      "edit": true,
      "imageSize": "2K",
      "note": "up to 4 character-consistency refs + 10 object refs"
    },
    "local_files": {
      "model": "gemini-3.1-flash-image"
    },
    "enabled": true,
    "sort": 61
  },
  {
    "id": "nano-banana-2-lite",
    "family": "gemini",
    "display_name": "Nano Banana 2 Lite",
    "kind": "image",
    "provider": "google",
    "modes": [
      "t2i",
      "edit"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "image",
      "usd": 0.0336,
      "estimate": true,
      "text_in": 0.3,
      "image_out": 30.0,
      "note": "1K only; batch is half"
    },
    "capabilities": {
      "multiRef": 14,
      "edit": true,
      "imageSize": "1K",
      "note": "object refs only — no character consistency, so identity will NOT hold across panels"
    },
    "local_files": {
      "model": "gemini-3.1-flash-lite-image"
    },
    "enabled": true,
    "sort": 62
  },
  {
    "id": "nano-banana-pro",
    "family": "gemini",
    "display_name": "Nano Banana Pro",
    "kind": "image",
    "provider": "google",
    "modes": [
      "t2i",
      "edit"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "image",
      "usd": 0.134,
      "estimate": true,
      "text_in": 0.3,
      "image_out": 120.0,
      "note": "$0.134 at 1K/2K, $0.24 at 4K; batch is half"
    },
    "capabilities": {
      "multiRef": 14,
      "edit": true,
      "imageSize": "2K",
      "note": "up to 5 character refs + 6 object + 3 style"
    },
    "local_files": {
      "model": "gemini-3-pro-image"
    },
    "enabled": true,
    "sort": 63
  },
  {
    "id": "seedream-5-pro",
    "family": "seedream",
    "display_name": "Seedream 5.0 Pro",
    "kind": "image",
    "provider": "fal",
    "modes": [
      "t2i",
      "edit"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "image",
      "usd": 0.075,
      "note": "<=2.36MP; $0.150 above; extra refs $0.003-0.005"
    },
    "capabilities": {
      "multiRef": 14,
      "edit": true,
      "adapter": "seedream",
      "blocked": "the studio has no key for this provider yet — add your own under API keys"
    },
    "local_files": {
      "adapter": "seedream",
      "endpoint": "fal-ai/bytedance/seedream/v5/pro"
    },
    "enabled": false,
    "sort": 65
  },
  {
    "id": "seedream-5-lite",
    "family": "seedream",
    "display_name": "Seedream 5.0 Lite",
    "kind": "image",
    "provider": "fal",
    "modes": [
      "t2i",
      "edit"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "image",
      "usd": 0.035,
      "note": "reasoning + up to 14 references"
    },
    "capabilities": {
      "multiRef": 14,
      "edit": true,
      "adapter": "seedream",
      "blocked": "the studio has no key for this provider yet — add your own under API keys"
    },
    "local_files": {
      "adapter": "seedream",
      "endpoint": "fal-ai/bytedance/seedream/v5/lite"
    },
    "enabled": false,
    "sort": 66
  },
  {
    "id": "minimax-music3-local",
    "family": "minimax-music3",
    "display_name": "MiniMax Music 3",
    "kind": "audio",
    "provider": "local",
    "modes": [
      "t2m"
    ],
    "sizes": null,
    "max_seconds": 360,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "lyrics": true,
      "instrumental": true,
      "sectionTags": true,
      "sampleRate": 44100,
      "attribution": "MiniMax Music 3",
      "promptStyle": "caption",
      "note": "Full songs to 5 minutes with sung vocals. The caption wants three parts — global metadata (genre, BPM, key, emotional arc), vocal details (gender, timbre, delivery) and arrangement. Lyrics take [Intro]/[Verse]/[Chorus]/[Bridge]/[Outro] section tags. Duration is a CEILING: the model plans its own length and often finishes early."
    },
    "local_files": {
      "family": "music3",
      "unet": "minimax_music3_dit_fp16.safetensors",
      "text_encoder": "minimax_music3_text_encoder_pruned_int8_convrot.safetensors",
      "clip_type": "minimax",
      "vae": "minimax_music3_dav.safetensors",
      "steps": 30,
      "cfg": 1.7,
      "sampler": "euler",
      "scheduler": "simple",
      "lm_cfg": 1.7,
      "top_k": 50,
      "max_seconds": 360,
      "sample_rate": 44100
    },
    "enabled": true,
    "sort": 40
  },
  {
    "id": "acestep-1.5-local",
    "family": "acestep",
    "display_name": "ACE-Step 1.5 · Turbo",
    "kind": "audio",
    "provider": "local",
    "modes": [
      "t2m"
    ],
    "sizes": null,
    "max_seconds": 300,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "lyrics": true,
      "instrumental": true,
      "sectionTags": true,
      "musicalMeta": true,
      "sampleRate": 48000,
      "turbo": true,
      "promptStyle": "tags",
      "note": "Tag-driven rather than prose: comma-separated genre/instrument/mood tags, with BPM, key, time signature and language as separate typed controls the encoder actually conditions on. Distilled to 8 steps. `generate_audio_codes` runs the 5Hz planner LM — on gives better song structure, off is faster and widens genre variety."
    },
    "local_files": {
      "family": "acestep",
      "unet": "acestep_v1.5_turbo.safetensors",
      "text_encoders": [
        "qwen_0.6b_ace15.safetensors",
        "qwen_1.7b_ace15.safetensors"
      ],
      "clip_type": "ace",
      "vae": "ace_1.5_vae.safetensors",
      "steps": 8,
      "cfg": 1.0,
      "shift": 3.0,
      "sampler": "euler",
      "scheduler": "simple",
      "lm_cfg": 2.0,
      "max_seconds": 300,
      "sample_rate": 48000
    },
    "enabled": true,
    "sort": 41
  },
  {
    "id": "acestep-1.5-xl-local",
    "family": "acestep",
    "display_name": "ACE-Step 1.5 XL · Turbo",
    "kind": "audio",
    "provider": "local",
    "modes": [
      "t2m"
    ],
    "sizes": null,
    "max_seconds": 300,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "lyrics": true,
      "instrumental": true,
      "sectionTags": true,
      "musicalMeta": true,
      "sampleRate": 48000,
      "turbo": true,
      "promptStyle": "tags",
      "note": "Tag-driven rather than prose: comma-separated genre/instrument/mood tags, with BPM, key, time signature and language as separate typed controls the encoder actually conditions on. Distilled to 8 steps. `generate_audio_codes` runs the 5Hz planner LM — on gives better song structure, off is faster and widens genre variety. XL on the 4B planner, which follows a long prompt more closely than the 1.7B. First render on this row downloads ~18GB (XL DiT + the 4B planner)."
    },
    "local_files": {
      "family": "acestep",
      "unet": "acestep_v1.5_xl_turbo_bf16.safetensors",
      "text_encoders": [
        "qwen_0.6b_ace15.safetensors",
        "qwen_4b_ace15.safetensors"
      ],
      "clip_type": "ace",
      "vae": "ace_1.5_vae.safetensors",
      "steps": 8,
      "cfg": 1.0,
      "shift": 3.0,
      "sampler": "euler",
      "scheduler": "simple",
      "lm_cfg": 2.0,
      "max_seconds": 300,
      "sample_rate": 48000
    },
    "enabled": true,
    "sort": 42
  },
  {
    "id": "acestep-1.5-xl-sft-local",
    "family": "acestep",
    "display_name": "ACE-Step 1.5 XL · SFT",
    "kind": "audio",
    "provider": "local",
    "modes": [
      "t2m"
    ],
    "sizes": null,
    "max_seconds": 300,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "lyrics": true,
      "instrumental": true,
      "sectionTags": true,
      "musicalMeta": true,
      "sampleRate": 48000,
      "promptStyle": "tags",
      "note": "Tag-driven rather than prose: comma-separated genre/instrument/mood tags, with BPM, key, time signature and language as separate typed controls the encoder actually conditions on. `generate_audio_codes` runs the 5Hz planner LM — on gives better song structure, off is faster and widens genre variety. Not distilled — 50 steps at cfg 7, so it is roughly 6x the render of the turbo rows and the one to try when a turbo take sounds thin. First render downloads ~28GB."
    },
    "local_files": {
      "family": "acestep",
      "unet": "acestep_v1.5_xl_sft_bf16.safetensors",
      "text_encoders": [
        "qwen_0.6b_ace15.safetensors",
        "qwen_4b_ace15.safetensors"
      ],
      "clip_type": "ace",
      "vae": "ace_1.5_vae.safetensors",
      "steps": 50,
      "cfg": 7.0,
      "shift": 3.0,
      "sampler": "euler",
      "scheduler": "simple",
      "lm_cfg": 2.0,
      "max_seconds": 300,
      "sample_rate": 48000
    },
    "enabled": true,
    "sort": 43
  },
  {
    "id": "stable-audio-3-medium-local",
    "family": "stable-audio-3",
    "display_name": "Stable Audio 3 Medium",
    "kind": "audio",
    "provider": "local",
    "modes": [
      "t2sfx"
    ],
    "sizes": null,
    "max_seconds": 380,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "promptStyle": "prose",
      "turbo": true,
      "stereo": true,
      "categories": [
        "sfx",
        "one-shot",
        "instrument",
        "music"
      ],
      "note": "One sentence of sound design, not tags: name the source, the material and the action, then the space it happens in ('heavy steel hatch dragging open, pneumatic hiss, long concrete reverb'). End with the length in seconds — the model was trained on captions that state it. Stereo out. Distilled to 8 steps at cfg 1, so a 3-second hit is a few seconds of GPU. No negative prompt: at cfg 1 the negative branch cannot contribute — use the BASE row for that. First render downloads ~10GB."
    },
    "local_files": {
      "family": "stable_audio",
      "checkpoint": "stable_audio_3_medium.safetensors",
      "text_encoder": "t5gemma_b_b_ul2.safetensors",
      "clip_type": "stable_audio",
      "steps": 8,
      "cfg": 1.0,
      "sampler": "lcm",
      "scheduler": "simple",
      "max_seconds": 380,
      "sample_rate": 44100
    },
    "enabled": true,
    "sort": 45
  },
  {
    "id": "stable-audio-3-medium-base-local",
    "family": "stable-audio-3",
    "display_name": "Stable Audio 3 Medium · Base",
    "kind": "audio",
    "provider": "local",
    "modes": [
      "t2sfx"
    ],
    "sizes": null,
    "max_seconds": 380,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "promptStyle": "prose",
      "stereo": true,
      "negativePrompt": true,
      "categories": [
        "sfx",
        "one-shot",
        "instrument",
        "music"
      ],
      "note": "One sentence of sound design, not tags: name the source, the material and the action, then the space it happens in ('heavy steel hatch dragging open, pneumatic hiss, long concrete reverb'). End with the length in seconds — the model was trained on captions that state it. Stereo out. Not distilled — 50 steps at cfg 7, so it is roughly 6x the render of the turbo row, and the only SFX row whose negative prompt is live. First render downloads ~10GB."
    },
    "local_files": {
      "family": "stable_audio",
      "checkpoint": "stable_audio_3_medium_base.safetensors",
      "text_encoder": "t5gemma_b_b_ul2.safetensors",
      "clip_type": "stable_audio",
      "steps": 50,
      "cfg": 7.0,
      "sampler": "lcm",
      "scheduler": "simple",
      "negative": true,
      "max_seconds": 380,
      "sample_rate": 44100
    },
    "enabled": true,
    "sort": 46
  },
  {
    "id": "stable-audio-3-small-sfx-local",
    "family": "stable-audio-3",
    "display_name": "Stable Audio 3 Small · SFX",
    "kind": "audio",
    "provider": "local",
    "modes": [
      "t2sfx"
    ],
    "sizes": null,
    "max_seconds": 120,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "promptStyle": "prose",
      "turbo": true,
      "stereo": true,
      "categories": [
        "sfx",
        "one-shot"
      ],
      "note": "One sentence of sound design, not tags: name the source, the material and the action, then the space it happens in ('heavy steel hatch dragging open, pneumatic hiss, long concrete reverb'). End with the length in seconds — the model was trained on captions that state it. Stereo out. The small effects-specialist checkpoint — 2.3GB against Medium's 9.2GB, capped at 2 minutes. First render downloads ~3.5GB."
    },
    "local_files": {
      "family": "stable_audio",
      "checkpoint": "stable_audio_3_small_sfx.safetensors",
      "text_encoder": "t5gemma_b_b_ul2.safetensors",
      "clip_type": "stable_audio",
      "steps": 8,
      "cfg": 1.0,
      "sampler": "lcm",
      "scheduler": "simple",
      "max_seconds": 120,
      "sample_rate": 44100
    },
    "enabled": true,
    "sort": 47
  },
  {
    "id": "mmaudio-large-44k-v2-local",
    "family": "mmaudio",
    "display_name": "MMAudio · Large 44k v2",
    "kind": "audio",
    "provider": "local",
    "modes": [
      "v2a"
    ],
    "sizes": null,
    "max_seconds": 30,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "promptStyle": "prose",
      "stereo": false,
      "video2audio": true,
      "steps": 25,
      "cfg": 4.5,
      "negativePrompt": true,
      "trainedSeconds": 8.0,
      "syncFps": 25,
      "note": "Scores a SILENT CLIP: it watches the frames and writes a synchronised soundtrack, so footsteps land on the footfall. The prompt names the sources you want ('boots on wet gravel, distant traffic'); the negative keeps things out ('music, speech'). Trained on 8-second videos — 5-12s is the band where sync holds. First render downloads ~5.1GB plus a 500MB vocoder."
    },
    "local_files": {
      "family": "mmaudio",
      "model": "mmaudio_large_44k_v2_fp16.safetensors",
      "vae": "mmaudio_vae_44k_fp16.safetensors",
      "synchformer": "mmaudio_synchformer_fp16.safetensors",
      "clip": "apple_DFN5B-CLIP-ViT-H-14-384_fp16.safetensors",
      "precision": "fp16",
      "mode": "44k",
      "sync_fps": 25,
      "clip_fps": 8,
      "steps": 25,
      "cfg": 4.5,
      "max_seconds": 30.0,
      "trained_seconds": 8.0,
      "sample_rate": 44100,
      "negative": true,
      "extra_nodes": [
        "https://github.com/kijai/ComfyUI-MMAudio",
        "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite"
      ]
    },
    "enabled": true,
    "sort": 48
  },
  {
    "id": "openai-tts",
    "family": "openai-tts",
    "display_name": "OpenAI · gpt-4o-mini-tts",
    "kind": "audio",
    "provider": "openai",
    "modes": [
      "tts"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "mtok",
      "usd": 0.6,
      "estimate": true,
      "note": "billed per character of input"
    },
    "capabilities": {
      "voices": [
        "alloy",
        "echo",
        "fable",
        "onyx",
        "nova",
        "shimmer"
      ],
      "delivery": "instructions",
      "note": "Six stock voices, no cloning. Delivery is passed as a plain instruction ('whispered, urgent'), so it takes prose rather than tags. The dependable default for narration."
    },
    "local_files": null,
    "enabled": true,
    "sort": 50
  },
  {
    "id": "elevenlabs-v3",
    "family": "elevenlabs",
    "display_name": "ElevenLabs v3",
    "kind": "audio",
    "provider": "elevenlabs",
    "modes": [
      "tts"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "mtok",
      "usd": 30.0,
      "estimate": true,
      "note": "billed per character; v3 is the expressive tier"
    },
    "capabilities": {
      "castVoices": true,
      "delivery": "tags",
      "cloning": "hosted",
      "note": "The voices the pipeline casts characters into, so a line auditioned here is the take the episode will get. Delivery compiles to a v3 audio tag ([whispers], [angry]). It clones too, and this is the only engine whose clone can be CAST onto a character — what it returns is an ordinary voice id, so the whole episode's dialogue can speak in it."
    },
    "local_files": null,
    "enabled": true,
    "sort": 51
  },
  {
    "id": "fish-s2",
    "family": "fish",
    "display_name": "Fish Audio · S2 (hosted)",
    "kind": "audio",
    "provider": "fish",
    "modes": [
      "tts"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "mtok",
      "usd": 15.0,
      "estimate": true,
      "note": "billed per character by Fish Audio"
    },
    "capabilities": {
      "cloning": "hosted",
      "delivery": "none",
      "note": "Speaks as a cloned voice. The reference clip is registered with Fish once and every later line cites the id it returns, so cloning here is a one-time upload. Needs a Fish Audio key (add your own under API keys). No territory or non-commercial restriction."
    },
    "local_files": null,
    "enabled": true,
    "sort": 52
  },
  {
    "id": "fish-s2-local",
    "family": "fish",
    "display_name": "Fish Speech S2-Pro (local)",
    "kind": "audio",
    "provider": "local",
    "modes": [
      "tts"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "cloning": "zero-shot",
      "delivery": "tags",
      "local": true,
      "note": "Zero-shot cloning — no registration, the reference clip IS the voice and is read at every line. Free per use and private. LICENCE: Fish Audio Research (NON-COMMERCIAL); the hosted row has no such restriction. 11GB of weights plus its own venv."
    },
    "local_files": null,
    "enabled": false,
    "sort": 55
  },
  {
    "id": "voxtral-4b-tts",
    "family": "voxtral",
    "display_name": "Voxtral 4B TTS",
    "kind": "audio",
    "provider": "voxtral",
    "modes": [
      "tts"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "mtok",
      "usd": 0,
      "estimate": true,
      "note": "free on a local vLLM-Omni serve; billed per character on Mistral's hosted endpoint"
    },
    "capabilities": {
      "cloning": "none",
      "delivery": "none",
      "voices": [
        "neutral_female",
        "neutral_male",
        "casual_female",
        "casual_male",
        "cheerful_female"
      ],
      "note": "20 preset voices as fixed voice EMBEDDINGS (5 English, plus a male/female pair per supported language) — expression is the preset, and there are no inline performance tags, so a line's delivery note cannot reach it. 24kHz. Needs VOXTRAL_BASE_URL. LICENCE: CC-BY-NC (NON-COMMERCIAL) — the weights and the reference voices both."
    },
    "local_files": null,
    "enabled": false,
    "sort": 56
  },
  {
    "id": "breeze-tts-2",
    "family": "breeze",
    "display_name": "Breeze TTS 2 (local)",
    "kind": "audio",
    "provider": "local",
    "modes": [
      "tts"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "castVoices": true,
      "cloning": "zero-shot",
      "delivery": "instruction",
      "local": true,
      "vocalEvents": [
        "laugh",
        "sigh",
        "cough",
        "clears throat"
      ],
      "note": "The voices the pipeline now designs characters into, from the writer's own description — so a line auditioned here is the take the episode gets. Delivery is an open-language instruction ('speak slowly, restrained'), not a tag, and '(sigh)' in the text is performed. Zero-shot cloning from any clip (the transcript is read off it if you don't type one). Runs in the studio cloud or on this machine; free per use. LICENCE: BreezeBlue Research (NON-COMMERCIAL) — the weights and their outputs."
    },
    "local_files": null,
    "enabled": true,
    "sort": 53
  },
  {
    "id": "qwen3-tts",
    "family": "qwen3-tts",
    "display_name": "Qwen3-TTS 1.7B (local)",
    "kind": "audio",
    "provider": "local",
    "modes": [
      "tts"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "castVoices": true,
      "cloning": "zero-shot",
      "delivery": "none",
      "local": true,
      "vocalEvents": [],
      "note": "Designs a character's voice from the writer's description and clones every line from that clip, exactly as Breeze does — and APACHE 2.0, weights and outputs, where Breeze's are non-commercial. Two checkpoints (~9GB): VoiceDesign designs, Base clones, and neither can do the other's job. It cannot steer a line's delivery (no instruction input on the clone) and does not perform '(sigh)', so a delivery note reaches the read through punctuation alone. About 9s to design a voice and 4s a line on a large GPU, 24kHz mono, and a cloned line stays close to its designed voice. Runs in the studio cloud or on this machine; free per use."
    },
    "local_files": null,
    "enabled": true,
    "sort": 54
  },
  {
    "id": "claude-api",
    "family": "claude",
    "display_name": "Claude (API key)",
    "kind": "llm",
    "provider": "anthropic",
    "modes": [],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "mtok",
      "usd": 5.0,
      "note": "claude-opus-5: $5/MTok in · $25/MTok out"
    },
    "capabilities": {
      "streaming": true,
      "tools": true
    },
    "local_files": null,
    "enabled": true,
    "sort": 71
  },
  {
    "id": "ollama-local",
    "family": "qwen3",
    "display_name": "Ollama (on this machine)",
    "kind": "llm",
    "provider": "ollama",
    "modes": [],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "local": true,
      "tools": true
    },
    "local_files": null,
    "enabled": true,
    "sort": 72
  },
  {
    "id": "openai-compat",
    "family": "custom",
    "display_name": "OpenAI-compatible endpoint",
    "kind": "llm",
    "provider": "openai",
    "modes": [],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "depends on endpoint (default gpt-4o-mini $0.15/$0.60 per MTok)"
    },
    "capabilities": {
      "streaming": true
    },
    "local_files": null,
    "enabled": true,
    "sort": 73
  },
  {
    "id": "text-embedding-3-small",
    "family": "openai",
    "display_name": "text-embedding-3-small",
    "kind": "embed",
    "provider": "openai",
    "modes": [],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "unit": "mtok",
      "usd": 0.02,
      "estimate": true
    },
    "capabilities": {},
    "local_files": null,
    "enabled": true,
    "sort": 80
  },
  {
    "id": "seedvr2-3b",
    "family": "seedvr2",
    "display_name": "SeedVR2 3B fp8 (restore/upscale)",
    "kind": "post",
    "provider": "local",
    "modes": [
      "upscale"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "batchRule": "4n+1",
      "temporal": true
    },
    "local_files": null,
    "enabled": true,
    "sort": 90
  },
  {
    "id": "rife47",
    "family": "rife",
    "display_name": "RIFE 4.7 (interpolate)",
    "kind": "post",
    "provider": "local",
    "modes": [
      "interpolate"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {},
    "local_files": null,
    "enabled": true,
    "sort": 91
  },
  {
    "id": "facedetailer",
    "family": "impact",
    "display_name": "FaceDetailer (hero shots)",
    "kind": "post",
    "provider": "local",
    "modes": [
      "facefix"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {
      "perFrame": true,
      "flickerRisk": true
    },
    "local_files": null,
    "enabled": true,
    "sort": 92
  },
  {
    "id": "vrgdg-grain-color",
    "family": "vrgdg",
    "display_name": "Film grain + color match (de-AI)",
    "kind": "post",
    "provider": "local",
    "modes": [
      "grain",
      "colormatch",
      "sharpen"
    ],
    "sizes": null,
    "max_seconds": null,
    "fps": null,
    "frame_base": null,
    "frame_rem": null,
    "dim_step": null,
    "pricing": {
      "note": "runs on this machine"
    },
    "capabilities": {},
    "local_files": null,
    "enabled": true,
    "sort": 93
  }
];

export default CATALOG;
