// The Workflows view — what ComfyUI graph each model actually renders on.
//
// READ-ONLY, on purpose. Editing or importing a graph means executing
// user-authored nodes on the shared $3.36/hr pod, which is a different
// security posture than anything else in the app; this ships the half that
// answers the question ("which workflow runs for H3 i2v, and what does it
// let me control?") without taking that on.
//
// WHERE THE DATA COMES FROM. Both halves are bundled from the repo at build
// time — the templates via import.meta.glob and model_map.full.json directly —
// rather than read from the pod or the DB. Three reasons, in order:
//   * the browser cannot talk to ComfyUI (invariant #1), so the pod is not an
//     option for a page that has to work while the box is asleep;
//   * `model_catalog.local_files` is a MIRROR of model_map synced by
//     scripts/gen_model_catalog.py, while the worker reads the deployed copy
//     of model_map itself — so the file is the truth and the table is the copy;
//   * bundling both from one git tree makes them consistent by construction.
//     The pod gets the same tree through the B2 tarball, so what this page
//     shows is what the worker loads, as long as both are deployed from the
//     same commit. That caveat is printed on the page rather than assumed.
//
// It is React.lazy'd in Workspace, unlike its sibling views: the glob inlines
// ~240KB of template JSON, which has no business in the main bundle for a tab
// most accounts cannot see.
import React, { useEffect, useMemo, useState } from "react";
import {
  AlertTriangle, Check, Copy, ExternalLink, FileJson, Globe, Image, Layers, Minus,
  Trash2, Workflow,
} from "lucide-react";
import { isDesktop } from "../../lib/desktop";
import {
  DEFAULT_COMFY as LOCAL_COMFY, editInComfy, importFromComfy, openComfy, savedInComfy,
} from "../../lib/comfyLocal";
import type { StagedWorkflow } from "../../lib/desktop";
import type { ApiGraph, UiGraph } from "../../lib/workflowAdapter";
import { useLocalEngine } from "../../hooks/useLocalEngine";
import { localRecipeRows, recipeSources, type LocalRecipeRow } from "../../lib/localModels";
import { loadCatalog } from "../../lib/catalog";
import { modelKeyOf } from "../../lib/projectSettings";
import { useLiveQuery } from "../../hooks/useLiveQuery";
import { useWorkspaceStore } from "../../stores/useWorkspaceStore";
import { deleteWorkflow, loadWorkflows, type CustomWorkflow } from "../../lib/db/customWorkflows";
import WorkflowRepairPanel from "./WorkflowRepairPanel";
import type { ModelCatalogRow } from "../../lib/db/types";
import modelMapJson from "../../../infra/model_map.full.json";
import modelMapDesktopJson from "../../../infra/model_map.desktop.json";
import {
  HANDLER_TEMPLATES, HEALTH_ORDER, contractOf, imageFamilies, mapProvenance, parseTemplate,
  pinContract, substitutionContract, templateRows, workflowUsage,
  type ContractRow, type MapProvenance, type ModelMap, type TemplateHealth,
  type TemplateRow, type WorkflowNode,
} from "../../lib/workflows";

/**
 * The two model maps this build carries, and what each one describes.
 *
 * `desktop` is what THIS MACHINE can resolve: the full map minus every entry
 * whose weights the engine window cannot fetch, generated by
 * `scripts/gen_desktop_model_map.mjs` and re-checked by a test. `full` is what
 * the pipeline can do given every weight — the source that generator prunes,
 * and the answer to "why is X not on the list", since it records a reason for
 * everything it dropped (see `mapProvenance`).
 *
 * The machine you are on is the default; the other is one click away.
 */
interface TierChoice {
  id: string;
  /** what the switch shows — `id` is the map key and is not a name */
  label: string;
  /** what runs the graphs on this tier — used in the sentence, not as a label */
  where: string;
  blurb: string;
  /** raw, because `mapProvenance` reads keys that are siblings of the tier */
  map: unknown;
}

const TIERS: TierChoice[] = [
  {
    id: "full",
    label: "Full map",
    where: "a machine with every weight",
    blurb: "Every entry the pipeline knows how to resolve, weights and node packs "
      + "assumed. It is the source the desktop map is generated from — useful for "
      + "answering why something is missing there, not for what runs here. A graph "
      + "cannot be edited on this tier.",
    map: modelMapJson,
  },
  {
    id: "desktop",
    label: "This machine",
    where: "this machine",
    blurb: "The same templates, resolved against the desktop model map — the full map "
      + "minus every entry whose weights the engine window cannot download. A block "
      + "rendered here runs the graph below on your own ComfyUI; everything the composer "
      + "renders locally is built in code instead, which is what Local recipes below are. "
      + "A graph cannot be edited here.",
    map: modelMapDesktopJson,
  },
];

const INK_MUTE = "#5e6678";
const C_OK = "#6fd08c";
const C_RISK = "#e8a13a";
const C_BROKEN = "#e8734a";

/** Raw text, not parsed JSON: post_rife.json is only valid JSON after its
 *  handler substitutes the `__HOLE__` markers, so the parser has to see the
 *  file exactly as the worker opens it. */
const RAW = import.meta.glob("../../../workflows/*.json", {
  query: "?raw", import: "default", eager: true,
}) as Record<string, string>;

const HEALTH_COLOR: Record<TemplateHealth, string> = {
  ok: C_OK, warn: C_RISK, broken: C_BROKEN, unused: INK_MUTE,
};
const HEALTH_LABEL: Record<TemplateHealth, string> = {
  ok: "in use", warn: "stub", broken: "broken", unused: "unused",
};

function Badge({ color, children, title }: {
  color: string; children: React.ReactNode; title?: string;
}) {
  return (
    <span className="mono" title={title} style={{
      fontSize: 10, padding: "2px 6px", borderRadius: 6, whiteSpace: "nowrap",
      color, background: `${color}1a`, border: `1px solid ${color}3d`,
    }}>{children}</span>
  );
}

/** One line of the contract. The icon carries the status as well as the
 *  colour — identity is never colour-alone. */
function ContractLine({ row }: { row: ContractRow }) {
  const color = row.status === "ok" ? C_OK : row.status === "risk" ? C_RISK : INK_MUTE;
  const Icon = row.status === "ok" ? Check : row.status === "risk" ? AlertTriangle : Minus;
  return (
    <div style={{ display: "flex", gap: 8, alignItems: "flex-start", padding: "5px 0" }}>
      <Icon size={13} style={{ color, flex: "none", marginTop: 2 }} />
      <div style={{ minWidth: 0 }}>
        <span style={{ fontSize: 12.5, fontWeight: 600 }}>{row.label}</span>
        <span style={{ fontSize: 12, color: row.status === "risk" ? "#eaeef6" : INK_MUTE }}>
          {" — "}{row.detail}
        </span>
      </div>
    </div>
  );
}

/** The template as the worker reads it. A placeholder template is not valid
 *  JSON until its handler substitutes, so this can fail — the caller only
 *  offers the button on `format === "api"`, which already excludes those. */
function apiOf(raw: string): ApiGraph | null {
  try {
    const g = JSON.parse(raw) as Record<string, unknown>;
    return Object.fromEntries(
      Object.entries(g).filter(([k]) => !k.startsWith("_"))) as ApiGraph;
  } catch { return null; }
}

/** A node's inputs, with links rendered as the node they come from. Literals
 *  are what resolve() overwrites, so they are worth seeing next to the
 *  contract that says whether it will. */
function inputSummary(n: WorkflowNode): string {
  const parts: string[] = [];
  for (const [k, v] of Object.entries(n.inputs)) {
    if (Array.isArray(v) && v.length === 2 && typeof v[0] === "string") parts.push(`${k}→#${v[0]}`);
    else if (typeof v === "string") parts.push(`${k}=${v.length > 34 ? `${v.slice(0, 33)}…` : v}`);
    else if (typeof v === "number" || typeof v === "boolean") parts.push(`${k}=${v}`);
    else parts.push(k);
  }
  return parts.join("  ");
}

const SideHead = ({ children }: { children: React.ReactNode }) => (
  <div className="mono" style={{
    fontSize: 10, color: INK_MUTE, padding: "12px 4px 6px", letterSpacing: "0.04em",
  }}>{children}</div>
);

function SideItem({ on, onClick, name, sub }: {
  on: boolean; onClick: () => void; name: string; sub: React.ReactNode;
}) {
  return (
    <button onClick={onClick} style={{
      display: "block", width: "100%", textAlign: "left", padding: "7px 9px",
      borderRadius: 10, marginBottom: 2,
      background: on ? "rgba(90,162,255,0.13)" : "transparent",
      color: on ? "#5aa2ff" : "#eaeef6",
    }}>
      <span className="mono" style={{
        fontSize: 11.5, display: "block", overflow: "hidden",
        textOverflow: "ellipsis", whiteSpace: "nowrap",
      }}>{name}</span>
      <span style={{ fontSize: 10, display: "block" }}>{sub}</span>
    </button>
  );
}

/**
 * Send this graph to ComfyUI's editor.
 *
 * It reports where the file LANDED rather than claiming the editor opened it,
 * because it did not: this frontend has no URL intent for a workflow, so what
 * happens is that the file appears in ComfyUI's own Workflows sidebar. Saying
 * "opened in ComfyUI" and leaving someone staring at their last graph is the
 * kind of small lie that makes a feature read as broken.
 */
function EditInComfyButton({ name, source }: {
  name: string;
  source: { ui?: UiGraph | null; api?: ApiGraph | null };
}) {
  const engine = useLocalEngine();
  const [busy, setBusy] = useState(false);
  const [done, setDone] = useState<
    { file: string; note: string; opened: boolean; kept: boolean } | null>(null);
  const [err, setErr] = useState<string | null>(null);
  if (!engine.desktop) return null;

  const go = async (fresh = false) => {
    setBusy(true); setErr(null); setDone(null);
    try {
      const r = await editInComfy(name, source, { fresh });
      // KEPT means ComfyUI already had an edited copy and we did not touch it.
      // Saying "converted from API format" there would describe a document
      // that is not the one on screen.
      if (r.kept) {
        setDone({
          file: r.file, opened: r.opened, kept: true,
          note: "your edited copy is what opened — nothing was overwritten",
        });
        return;
      }
      setDone({
        file: r.file, opened: r.opened, kept: false,
        note: r.unmapped.length
          ? `${r.unmapped.length} node type${r.unmapped.length > 1 ? "s" : ""} the engine `
            + `does not have (${r.unmapped.slice(0, 3).join(", ")}) kept their shape but not `
            + "their values — install the pack and send it again"
          : r.native ? "the author's own layout, staged as-is"
          : "converted from API format, so the layout is generated",
      });
    } catch (e) {
      setErr(e instanceof Error ? e.message : String(e));
    } finally { setBusy(false); }
  };

  return (
    <>
      <button className="ws-actbtn" onClick={() => void go(false)}
        disabled={busy || !engine.running}
        title={engine.running
          ? "Convert if needed, put it in ComfyUI's own workflow list, and open ComfyUI"
          : "Start your engine first — the widget order comes from the running ComfyUI"}
        style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 11.5 }}>
        <ExternalLink size={12} />{busy ? "Sending…" : "Edit in ComfyUI"}
      </button>
      {(done || err) && (
        <div style={{
          marginTop: 10, fontSize: 12, padding: "8px 10px", borderRadius: 10, width: "100%",
          color: err ? "#f0b9a4" : "#c7cddb",
          background: err ? "rgba(232,115,74,0.09)" : "rgba(255,255,255,0.035)",
          border: `1px solid ${err ? "rgba(232,115,74,0.28)" : "rgba(255,255,255,0.07)"}`,
        }}>
          {err ?? <>
            {done!.opened ? "Opened in ComfyUI as " : "Saved as "}
            <span className="mono">{done!.file}</span>
            {done!.opened
              ? <> — it is in the <b>Workflows</b> sidebar there too.</>
              : <> — open ComfyUI's <b>Workflows</b> sidebar (press{" "}
                  <span className="mono">w</span>) and click it.</>}
            <span style={{ color: INK_MUTE }}> {done!.note}.</span>
            {done!.kept && (
              <div style={{ marginTop: 8, display: "flex", gap: 8, alignItems: "center" }}>
                <span style={{ color: INK_MUTE, fontSize: 11.5 }}>
                  Import it from <b>In ComfyUI</b> to bring those changes back, or
                </span>
                <button className="ws-actbtn" onClick={() => void go(true)} disabled={busy}
                  title="Replace ComfyUI's copy with a fresh conversion — your edits there are lost"
                  style={{ fontSize: 11.5 }}>
                  Start over from this graph
                </button>
              </div>
            )}
          </>}
        </div>
      )}
    </>
  );
}

function CopyButton({ text, label }: { text: string; label: string }) {
  const [done, setDone] = useState(false);
  return (
    <button
      className="ws-actbtn"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(text);
          setDone(true);
          setTimeout(() => setDone(false), 1400);
        } catch { /* clipboard blocked — the raw JSON is on screen anyway */ }
      }}
      style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 11.5 }}
    >
      {done ? <Check size={12} /> : <Copy size={12} />}{done ? "Copied" : label}
    </button>
  );
}

/**
 * What a GENERATED map could not carry, in the generator's own words.
 *
 * Collapsed to one line, because this is the question you only ask once you
 * have noticed the tier looks thin — and thin is exactly how the desktop tier
 * looks (four reachable templates against the pod's twelve) until you read it.
 * `scripts/gen_desktop_model_map.mjs` records a reason for every entry it
 * drops; leaving that in a file nobody opens is what made "the desktop can't
 * render Krea 2" a mystery rather than a sentence.
 */
function MapReport({ prov }: { prov: MapProvenance }) {
  const [open, setOpen] = useState(false);
  const sections = useMemo(() => {
    const out = new Map<string, { key: string; why: string }[]>();
    for (const d of prov.dropped) {
      out.set(d.section, [...(out.get(d.section) ?? []), { key: d.key, why: d.why }]);
    }
    return [...out.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  }, [prov]);

  const counts = [
    prov.dropped.length && `${prov.dropped.length} entries dropped`,
    prov.adaptersDropped.length && `${prov.adaptersDropped.length} adapter sets pruned`,
    prov.strippedKeys.length && `${prov.strippedKeys.length} keys stripped`,
  ].filter(Boolean).join(" · ");

  return (
    <div className="ws-card ns-l1" style={{ borderRadius: 14, padding: "10px 12px", marginBottom: 12 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
        <Layers size={13} style={{ color: INK_MUTE, flex: "none" }} />
        <span style={{ fontSize: 12.5 }}>
          This map is generated — <span style={{ color: INK_MUTE }}>{counts}</span>
        </span>
        <div style={{ flex: 1 }} />
        {/* The generator's own path is a repo detail and says nothing anyone
            reading this page can act on — the sentence beside it already
            carries the fact that matters, which is that the map is derived. */}
        <button className="ws-actbtn" onClick={() => setOpen((v) => !v)} style={{ fontSize: 11.5 }}>
          {open ? "Hide" : "What is missing"}
        </button>
      </div>

      {open && (
        <div style={{ marginTop: 10, display: "flex", flexDirection: "column", gap: 12 }}>
          {sections.map(([section, items]) => (
            <div key={section}>
              <div className="mono" style={{ fontSize: 10, color: INK_MUTE, marginBottom: 4 }}>
                {section.toUpperCase()} · {items.length}
              </div>
              {items.map((d) => (
                <div key={d.key} style={{ display: "flex", gap: 8, padding: "2px 0", fontSize: 11.5 }}>
                  <span className="mono" style={{ width: 176, flex: "none", color: "#eaeef6" }}>
                    {d.key}
                  </span>
                  <span style={{ color: INK_MUTE, minWidth: 0 }}>{d.why}</span>
                </div>
              ))}
            </div>
          ))}

          {prov.adaptersDropped.length > 0 && (
            <div>
              <div className="mono" style={{ fontSize: 10, color: INK_MUTE, marginBottom: 4 }}>
                ADAPTERS PRUNED — the file is not fetchable here, so the key is dropped
                rather than resolved to nothing
              </div>
              {prov.adaptersDropped.map((a) => (
                <div key={a.model} style={{ display: "flex", gap: 8, padding: "3px 0", flexWrap: "wrap" }}>
                  <span className="mono" style={{ width: 176, flex: "none", fontSize: 11.5 }}>
                    {a.model}
                  </span>
                  <span style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
                    {a.loras.map((l) => <Badge key={l} color={INK_MUTE}>{l}</Badge>)}
                  </span>
                </div>
              ))}
            </div>
          )}

          {prov.strippedKeys.length > 0 && (
            <div>
              <div className="mono" style={{ fontSize: 10, color: INK_MUTE, marginBottom: 4 }}>
                KEYS STRIPPED FROM EVERY ENTRY
              </div>
              {prov.strippedKeys.map((k) => (
                <div key={k.key} style={{ display: "flex", gap: 8, padding: "2px 0", fontSize: 11.5 }}>
                  <span className="mono" style={{ width: 176, flex: "none", color: "#eaeef6" }}>
                    {k.key}
                  </span>
                  <span style={{ color: INK_MUTE, minWidth: 0 }}>{k.why}</span>
                </div>
              ))}
            </div>
          )}

          {prov.from && (
            <div className="mono" style={{ fontSize: 10.5, color: INK_MUTE }}>
              derived from {prov.from}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default function WorkflowsView() {
  return <WorkflowsBody />;
}

/** Exported for `/ui/workflows`, which renders the page without the route
 *  around it — the claim worth reviewing here is a picture: that the header
 *  names the machine it is describing, and that switching tiers visibly
 *  changes what is in use. */
export function WorkflowsBody() {
  const ws = useWorkspaceStore();
  const [sel, setSel] = useState<string | null>(null);
  const [showRaw, setShowRaw] = useState(false);
  // Folded by default: on the desktop tier it is 17 of 22 rows, and the ones
  // worth acting on are counted in the heading either way.
  const [showDormant, setShowDormant] = useState(false);
  const [catalog, setCatalog] = useState<ModelCatalogRow[]>([]);

  // Imported graphs, live — an import from the hub (or a "Sync to Qamba" push
  // from ComfyUI) has to land in this list without a reload.
  const { data: imported } = useLiveQuery(
    () => loadWorkflows(null), ["custom_workflows"], []);

  // The machine you are on. A web build has no engine of its own, so it opens
  // on the full map; either tier stays one click away, since both ship in this
  // bundle.
  const [tier, setTier] = useState<string>(() => (isDesktop() ? "desktop" : "full"));
  const choice = TIERS.find((t) => t.id === tier) ?? TIERS[0];
  const mm = choice.map as ModelMap;
  const prov = useMemo(() => mapProvenance(choice.map), [choice]);
  const engine = useLocalEngine();

  useEffect(() => {
    loadCatalog().then(setCatalog).catch(() => { /* names are a nicety */ });
  }, []);

  const rows = useMemo(() => {
    const usage = workflowUsage(mm, tier);
    const parsed = Object.entries(RAW)
      .map(([p, text]) => parseTemplate(p.split("/").pop() ?? p, text))
      .sort((a, b) => a.name.localeCompare(b.name));
    return templateRows(parsed, usage, tier).sort((a, b) =>
      HEALTH_ORDER[a.health] - HEALTH_ORDER[b.health] || a.parsed.name.localeCompare(b.parsed.name));
  }, [mm, tier]);

  // Reachable templates lead. Sorting the whole list worst-first put ten
  // unused and stub files above every template that actually renders, which
  // buries the answer to the question the page is for; the audit is still
  // there, as its own group, where a count reads as a finding rather than as
  // the contents of the studio.
  const live = useMemo(() => rows.filter((r) => r.health !== "unused" && r.health !== "warn"), [rows]);
  const dormant = useMemo(() => rows.filter((r) => r.health === "unused" || r.health === "warn"), [rows]);

  const families = useMemo(() => imageFamilies(mm, tier), [mm, tier]);

  // THE DESKTOP'S OTHER RENDERER. `graphs.py`'s image builders are reachable
  // only where `image_gen` runs on Python, which is the pod — `plan_cli.KINDS`
  // has no such kind — so on the desktop tier those families are replaced by
  // the ones `localGraphs.ts` actually builds. Not gated on an engine being
  // present: this is what the BUILD can render, and what is downloaded rides
  // along as an annotation.
  const recipes = useMemo(
    () => (tier === "desktop" ? localRecipeRows(engine.status) : []),
    [tier, engine.status]);
  // A template no model_map names is dead weight on every tier — except when a
  // local recipe was ported from it, which is exactly the case for the Wan 5B
  // pair. Fact about the repo, so it is shown on both tiers.
  const portedInto = useMemo(() => recipeSources(), []);

  // WHY a template is dormant, which is the difference between an audit and a
  // wall. Most of the "not reachable" list is just "the other tier renders
  // this" — true, expected, and nothing to act on; what is worth surfacing is
  // the handful nothing anywhere references. Both are one lookup away, so the
  // list says which rather than lumping them under one word.
  const other = tier === "desktop" ? TIERS[0] : TIERS[1];
  const elsewhere = useMemo(() => {
    const named = new Set(workflowUsage(other.map as ModelMap, other.id).keys());
    for (const [file, h] of Object.entries(HANDLER_TEMPLATES)) {
      if (!h.tiers || h.tiers.includes(other.id)) named.add(file);
    }
    return named;
  }, [other]);
  const dormantWhy = (name: string): { text: string; finding: boolean } => {
    const into = portedInto.get(name);
    if (into) return { text: `ported into ${into.join(", ")}`, finding: false };
    if (elsewhere.has(name)) return { text: `renders on ${other.where}`, finding: false };
    return { text: "nothing references it", finding: true };
  };

  // THE RETURN TRIP. ComfyUI saves where it opened from, so an edit lands back
  // in its own workflows folder — polled rather than watched because it is one
  // readdir of a folder with a handful of files in it, and a watcher would be
  // a dependency plus a lifetime to get wrong. Only while this view is open:
  // this is the screen the import lands on.
  const [saved, setSaved] = useState<StagedWorkflow[]>([]);
  const [savedAt, setSavedAt] = useState(0);
  useEffect(() => {
    if (tier !== "desktop" || !engine.desktop) { setSaved([]); return; }
    let alive = true;
    const read = () => savedInComfy().then((x) => { if (alive) setSaved(x); }).catch(() => {});
    read();
    const t = setInterval(read, 4000);
    return () => { alive = false; clearInterval(t); };
  }, [tier, engine.desktop, savedAt]);

  /** model_map key → the catalog rows a user actually picks in the UI.
   *  `modelKeyOf` is the same guess the composer makes when it sends
   *  payload.model_key, so this is the real picker → workflow chain. */
  const catalogByKey = useMemo(() => {
    const out = new Map<string, ModelCatalogRow[]>();
    for (const r of catalog) {
      const k = modelKeyOf(r.id);
      if (!k) continue;
      out.set(k, [...(out.get(k) ?? []), r]);
    }
    return out;
  }, [catalog]);

  const custom = imported ?? [];
  const selCustom = sel?.startsWith("cw:")
    ? custom.find((w) => `cw:${w.id}` === sel) ?? null : null;
  const selRecipe = sel?.startsWith("rec:")
    ? recipes.find((r) => `rec:${r.family}` === sel) ?? null : null;
  const selSaved = sel?.startsWith("saved:")
    ? saved.find((w) => `saved:${w.file}` === sel) ?? null : null;
  const selected = rows.find((r) => r.parsed.name === sel)
    ?? (sel?.startsWith("img:") || sel?.startsWith("cw:") || sel?.startsWith("rec:")
      || sel?.startsWith("saved:")
      ? null : live[0] ?? rows[0]);
  const selFamily = sel?.startsWith("img:")
    ? families.find((f) => `img:${f.family}` === sel) ?? null : null;

  const trouble = rows.filter((r) => r.health === "broken").length;
  const orphans = dormant.filter((r) => dormantWhy(r.parsed.name).finding).length;
  const pick = (name: string) => { setSel(name); setShowRaw(false); };

  return (
    <>
      <div className="ws-viewhead">
        <span className="ws-h2">Workflows</span>
        <div className="ws-seg tiny" role="group" aria-label="render tier">
          {TIERS.map((t) => (
            <button key={t.id} className={t.id === tier ? "on" : ""}
              onClick={() => { setTier(t.id); setSel(null); }}
              title={`what ${t.where} renders these graphs with`}>
              {t.label}
            </button>
          ))}
        </div>
        <span className="mono" style={{ fontSize: 11, color: INK_MUTE }}>
          {rows.length} templates · {live.length} in use on {choice.where}
          {trouble > 0 && <b style={{ color: C_BROKEN }}> · {trouble} broken</b>}
        </span>
        <div style={{ flex: 1 }} />
        <button className="ws-actbtn"
                onClick={() => ws.openModal({ kind: "civitai", projectId: null })}
                title="Search Civitai for ComfyUI workflows and import one"
                style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 11.5 }}>
          <Globe size={12} />Import from Civitai
        </button>
        {tier === "full" ? (
          <span className="mono" style={{ fontSize: 11, color: INK_MUTE }}
                title="this tier describes a machine with every weight, not the one you are on">
            reference only
          </span>
        ) : engine.running ? (
          <button className="ws-actbtn" onClick={() => void openComfy()}
             title={`ComfyUI's own editor at ${LOCAL_COMFY}, in a window of this app's`}
             style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 11.5 }}>
            <ExternalLink size={12} />Open ComfyUI
          </button>
        ) : (
          <span className="mono" style={{ fontSize: 11, color: INK_MUTE }}
                title={engine.desktop
                  ? "the engine window starts it, or link the ComfyUI you already run"
                  : "these graphs run in the desktop app, on your own engine"}>
            ComfyUI · {engine.desktop ? "not running" : "desktop app only"}
          </span>
        )}
      </div>

      <p style={{ fontSize: 12, color: INK_MUTE, margin: "2px 4px 10px", maxWidth: 780 }}>
        {choice.blurb}
      </p>

      {prov && <MapReport prov={prov} />}

      <div style={{ display: "flex", gap: 14, alignItems: "flex-start" }}>
        <aside style={{ width: 258, flex: "none", position: "sticky", top: 0 }}>
          <SideHead>IN USE · {live.length}</SideHead>
          {live.map((r) => (
            <SideItem key={r.parsed.name} on={selected?.parsed.name === r.parsed.name && !selFamily}
              onClick={() => pick(r.parsed.name)} name={r.parsed.name.replace(/\.json$/, "")}
              sub={<span style={{ color: HEALTH_COLOR[r.health] }}>
                {HEALTH_LABEL[r.health]}
                {r.uses.length > 0 && (
                  <span style={{ color: INK_MUTE }}> · {r.uses.length} mode{r.uses.length > 1 ? "s" : ""}</span>
                )}
              </span>} />
          ))}

          {tier === "desktop" && (
            <>
              <SideHead>LOCAL RECIPES · {recipes.length}</SideHead>
              {recipes.map((r) => (
                <SideItem key={r.family} on={selRecipe?.family === r.family}
                  onClick={() => pick(`rec:${r.family}`)} name={r.family}
                  sub={<span style={{ color: r.installed ? C_OK : INK_MUTE }}>
                    {r.installed
                      ? `${r.installed} of ${r.variants.length} installed`
                      : "built in code"}
                    <span style={{ color: INK_MUTE }}> · {r.kind}</span>
                  </span>} />
              ))}
            </>
          )}

          {saved.length > 0 && <SideHead>IN COMFYUI · {saved.length}</SideHead>}
          {saved.map((w) => (
            <SideItem key={w.file} on={selSaved?.file === w.file}
              onClick={() => pick(`saved:${w.file}`)} name={w.file.replace(/\.json$/, "")}
              sub={<span style={{ color: INK_MUTE }}>
                {w.ours ? "sent from here" : "made in ComfyUI"} · {ago(w.modified_ms)}
              </span>} />
          ))}

          {custom.length > 0 && <SideHead>IMPORTED · {custom.length}</SideHead>}
          {custom.map((w) => (
            <SideItem key={w.id} on={selCustom?.id === w.id}
              onClick={() => pick(`cw:${w.id}`)} name={w.name}
              sub={<span style={{
                color: w.status === "ready" ? C_OK : w.status === "error" ? C_BROKEN : INK_MUTE,
              }}>
                {w.status}
                <span style={{ color: INK_MUTE }}> · {w.source}</span>
              </span>} />
          ))}

          {tier === "full" && (
            <>
              <SideHead>IMAGE FAMILIES · NO TEMPLATE</SideHead>
              {families.map((f) => (
                <SideItem key={f.family} on={selFamily?.family === f.family}
                  onClick={() => pick(`img:${f.family}`)} name={f.family}
                  sub={<span style={{ color: INK_MUTE }}>
                    built in code · {f.models.length} model{f.models.length > 1 ? "s" : ""}
                  </span>} />
              ))}
            </>
          )}

          {/* LAST, AND FOLDED. Every group above answers "what renders this?";
              this one is an audit of what does not, which is worth having and
              is not worth the top of the list — on the desktop tier it is 17
              of 22 rows, and it used to push the recipes off screen. */}
          {dormant.length > 0 && (
            <button onClick={() => setShowDormant((v) => !v)}
              title="Templates nothing on this tier resolves or names"
              style={{ display: "block", width: "100%", textAlign: "left", padding: "12px 4px 6px" }}>
              <span className="mono" style={{ fontSize: 10, color: INK_MUTE, letterSpacing: "0.04em" }}>
                NOT REACHABLE · {dormant.length} {showDormant ? "▾" : "▸"}
              </span>
              {/* The count alone reads as a studio full of dead files. Most of
                  it is the other tier's, which is not a finding; the orphans
                  are, so they are the half that gets said out loud. */}
              <span style={{ fontSize: 10, color: INK_MUTE, display: "block", marginTop: 2 }}>
                {orphans > 0
                  ? <b style={{ color: C_RISK }}>{orphans} referenced by nothing</b>
                  : "all accounted for"}
                {dormant.length - orphans > 0 && <> · {dormant.length - orphans} elsewhere</>}
              </span>
            </button>
          )}
          {showDormant && dormant.map((r) => {
            const why = dormantWhy(r.parsed.name);
            return (
              <SideItem key={r.parsed.name} on={selected?.parsed.name === r.parsed.name && !selFamily}
                onClick={() => pick(r.parsed.name)} name={r.parsed.name.replace(/\.json$/, "")}
                sub={<span style={{ color: why.finding ? C_RISK : INK_MUTE }}>{why.text}</span>} />
            );
          })}
        </aside>

        <section style={{ flex: 1, minWidth: 0 }}>
          {selCustom ? (
            <ImportedDetail w={selCustom} onDelete={async () => {
              await deleteWorkflow(selCustom.id);
              setSel(null);
            }} />
          ) : selSaved ? (
            <SavedInComfyDetail w={selSaved}
              onImported={(id) => { setSavedAt(Date.now()); setSel(`cw:${id}`); }} />
          ) : selRecipe ? (
            <LocalRecipeDetail row={selRecipe} onPick={pick} have={rows} />
          ) : selFamily ? (
            <div className="ws-card ns-l1" style={{ borderRadius: 18 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}>
                <Image size={14} style={{ color: INK_MUTE }} />
                <span className="mono" style={{ fontSize: 13.5, fontWeight: 600 }}>{selFamily.family}</span>
                <Badge color={INK_MUTE}>no template</Badge>
              </div>
              <p style={{ fontSize: 12.5, color: "#c7cddb", margin: "0 0 10px", maxWidth: 640 }}>
                Image jobs never load a JSON template. The graph is built in code from the
                model&rsquo;s <span className="mono">family</span>, fitting node inputs to the schema the
                engine reports and falling back to another family when a node is missing —
                which a static template could not express.
              </p>
              <div className="mono" style={{ fontSize: 11.5, color: C_OK, marginBottom: 10 }}>
                {selFamily.builder}
              </div>
              <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
                {selFamily.models.map((m) => (
                  <Badge key={m} color="#458de8">{m}</Badge>
                ))}
              </div>
            </div>
          ) : selected ? (
            <TemplateDetail
              row={selected}
              mm={mm}
              tier={tier}
              portedInto={portedInto.get(selected.parsed.name) ?? null}
              catalogByKey={catalogByKey}
              raw={RAW[Object.keys(RAW).find((p) => p.endsWith(`/${selected.parsed.name}`)) ?? ""] ?? ""}
              showRaw={showRaw}
              onToggleRaw={() => setShowRaw((v) => !v)}
            />
          ) : null}
        </section>
      </div>
    </>
  );
}

/**
 * An imported graph.
 *
 * It gets the SAME contract panel a bundled template gets, which is the point
 * of converting to API format on import: once a Civitai download is in the
 * studio's own dialect, `contractOf` can say what resolve() would be able to
 * drive on it — and next to that, the slot map says what the studio will drive
 * whether or not resolve() recognises the classes. Two different questions,
 * and an imported graph is exactly where they diverge.
 */
function ImportedDetail({ w, onDelete }: { w: CustomWorkflow; onDelete: () => void }) {
  // The row is refetched live, but a repair rewrites it and the panel already
  // has the answer — holding it locally means the slots and the error banner
  // update on the same tick as the fix rather than a socket round trip later.
  const [row, setRow] = useState<CustomWorkflow>(w);
  useEffect(() => { setRow(w); }, [w]);
  const nodes: WorkflowNode[] = useMemo(
    () => Object.entries(row.api_graph ?? {})
      .filter(([id]) => !id.startsWith("_"))
      .map(([id, n]) => ({ id, class_type: n.class_type, inputs: n.inputs ?? {} })),
    [row.api_graph]);
  const contract = useMemo(() => contractOf(nodes, {}), [nodes]);
  const s = row.slots ?? {};
  const slotRow = (label: string, v?: { node: string; input: string; class_type: string }) => (
    <div style={{ display: "flex", gap: 8, fontSize: 12, padding: "3px 0" }}>
      <span style={{ color: INK_MUTE, width: 96, flex: "none" }}>{label}</span>
      <span className="mono" style={{ fontSize: 11.5 }}>
        {v ? `${v.class_type} #${v.node}.${v.input}` : <span style={{ color: C_RISK }}>untagged</span>}
      </span>
    </div>
  );

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
      <div className="ws-card ns-l1" style={{ borderRadius: 18 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
          <Globe size={14} style={{ color: INK_MUTE }} />
          <span className="mono" style={{ fontSize: 13.5, fontWeight: 600 }}>{w.name}</span>
          <Badge color={w.status === "ready" ? C_OK : w.status === "error" ? C_BROKEN : INK_MUTE}>
            {w.status}
          </Badge>
          <Badge color="#aa5bde">{w.source}</Badge>
          {w.base_model && <Badge color="#458de8">{w.base_model}</Badge>}
          <span className="mono" style={{ fontSize: 10.5, color: INK_MUTE }}>
            {nodes.length} nodes{w.ui_graph ? " · UI graph kept" : ""}
          </span>
          <div style={{ flex: 1 }} />
          {w.source_url && (
            <a className="ws-actbtn" href={w.source_url} target="_blank" rel="noreferrer"
               style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 11.5 }}>
              <ExternalLink size={12} />Source
            </a>
          )}
          <EditInComfyButton name={w.name}
            source={{ ui: (w.ui_graph as UiGraph | null) ?? null, api: w.api_graph as ApiGraph }} />
          <CopyButton text={JSON.stringify(w.api_graph, null, 2)} label="Copy API JSON" />
          <button className="ws-actbtn" onClick={onDelete} title="Remove this workflow"
                  style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 11.5 }}>
            <Trash2 size={12} />
          </button>
        </div>

        <div style={{
          marginTop: 10, fontSize: 12, padding: "8px 10px", borderRadius: 10, color: "#c7cddb",
          background: "rgba(255,255,255,0.035)", border: "1px solid rgba(255,255,255,0.07)",
        }}>
          This graph runs: pick it in the composer&rsquo;s Workflow control and the render is
          driven by the slots below rather than by a model recipe, in the cloud or on
          this machine&rsquo;s own ComfyUI. What is here is the whole contract: the
          executable graph, the slots the studio writes into, and what the engine needs
          before it can run.
        </div>

        <div style={{ marginTop: 12 }}>
          <div className="mono" style={{ fontSize: 10, color: INK_MUTE, marginBottom: 6 }}>SLOTS</div>
          {slotRow("Prompt", s.prompt)}
          {s.negative && slotRow("Negative", s.negative)}
          {slotRow("Seed", s.seed)}
          <div style={{ display: "flex", gap: 8, fontSize: 12, padding: "3px 0" }}>
            <span style={{ color: INK_MUTE, width: 96, flex: "none" }}>Size</span>
            <span className="mono" style={{ fontSize: 11.5 }}>
              {s.size
                ? `${s.size.class_type} #${s.size.node} (${
                    [s.size.width, s.size.height, s.size.length].filter(Boolean).join(", ")})`
                : <span style={{ color: C_RISK }}>untagged</span>}
            </span>
          </div>
          {s.start_frame && slotRow("Start frame", s.start_frame)}
          {s.end_frame && slotRow("End frame", s.end_frame)}
          <div style={{ display: "flex", gap: 8, fontSize: 12, padding: "3px 0" }}>
            <span style={{ color: INK_MUTE, width: 96, flex: "none" }}>Output</span>
            <span className="mono" style={{ fontSize: 11.5 }}>
              {s.output?.length
                ? s.output.map((o) => `${o.class_type} #${o.node}`).join(", ")
                : <span style={{ color: C_BROKEN }}>none — nothing would be saved</span>}
            </span>
          </div>
        </div>

        {row.last_error && (
          <div style={{
            marginTop: 10, fontSize: 12, padding: "8px 10px", borderRadius: 10,
            color: "#f0b9a4", background: "rgba(232,115,74,0.09)",
            border: "1px solid rgba(232,115,74,0.28)",
          }}>
            {String((row.last_error as { message?: string }).message ?? JSON.stringify(row.last_error))}
          </div>
        )}
      </div>

      <WorkflowRepairPanel w={row} onChange={setRow} />

      {(w.requirements?.classes?.length ?? 0) > 0 && (
        <div className="ws-card ns-l1" style={{ borderRadius: 18 }}>
          <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 6 }}>Needs</div>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 5, marginBottom: 8 }}>
            {w.requirements.classes.map((c) => <Badge key={c} color={INK_MUTE}>{c}</Badge>)}
          </div>
          {!!w.requirements.files?.length && (
            <table className="mono" style={{ fontSize: 11, borderCollapse: "collapse", width: "100%" }}>
              <tbody>
                {w.requirements.files.map((f, i) => (
                  <tr key={i} style={{ borderTop: "1px solid rgba(255,255,255,0.05)" }}>
                    <td style={{ padding: "4px 10px 4px 0", color: INK_MUTE, whiteSpace: "nowrap" }}>
                      {f.input}
                    </td>
                    <td style={{ padding: "4px 0", wordBreak: "break-all" }}>{f.value}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}

      {contract.length > 0 && (
        <div className="ws-card ns-l1" style={{ borderRadius: 18 }}>
          <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 4 }}>
            What resolve() could set
          </div>
          <p style={{ fontSize: 11.5, color: INK_MUTE, margin: "0 0 8px", maxWidth: 700 }}>
            The same check the bundled templates get. An imported graph is under no
            obligation to satisfy it — the slots above are how the studio drives this
            one — but a row marked risk here is a parameter that would be dropped if
            it were ever wired to a model.
          </p>
          {contract.map((c) => <ContractLine key={c.id} row={c} />)}
        </div>
      )}
    </div>
  );
}

/** "3 minutes ago", for a list whose whole question is what changed last. */
function ago(ms: number): string {
  const s = Math.max(0, Math.round((Date.now() - ms) / 1000));
  if (s < 45) return "just now";
  const m = Math.round(s / 60);
  if (m < 60) return `${m}m ago`;
  const h = Math.round(m / 60);
  return h < 36 ? `${h}h ago` : `${Math.round(h / 24)}d ago`;
}

/**
 * A workflow sitting in ComfyUI, and the way back in.
 *
 * THE RETURN TRIP LANDS AS A `custom_workflows` ROW, NEVER AS AN EDIT TO A
 * TEMPLATE, and that is the whole shape of this feature rather than a
 * convenience: `resolve.py` parameterises the bundled templates by matching
 * `class_type`, which is safe only on graphs this repo wrote. An edited
 * template would still render and would silently stop taking the prompt, the
 * references or the LoRA stack — the failure this codebase keeps naming. A
 * user graph is driven by TAGGED SLOTS instead, which is what an import
 * produces and what both runners already know how to execute.
 */
function SavedInComfyDetail({ w, onImported }: {
  w: StagedWorkflow;
  onImported: (id: string) => void;
}) {
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const [note, setNote] = useState<string | null>(null);

  const go = async () => {
    setBusy(true); setErr(null); setNote(null);
    try {
      const r = await importFromComfy(w.file);
      setNote(r.replaced
        ? `Updated "${r.row.name}" — same row, so anything already pointing at it still resolves.`
        : `Imported as "${r.row.name}".`);
      onImported(r.row.id);
    } catch (e) {
      setErr(e instanceof Error ? e.message : String(e));
    } finally { setBusy(false); }
  };

  return (
    <div className="ws-card ns-l1" style={{ borderRadius: 18 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
        <FileJson size={14} style={{ color: INK_MUTE }} />
        <span className="mono" style={{ fontSize: 13.5, fontWeight: 600 }}>
          {w.file.replace(/\.json$/, "")}
        </span>
        <Badge color={w.ours ? "#458de8" : "#aa5bde"}>
          {w.ours ? "sent from here" : "made in ComfyUI"}
        </Badge>
        <span className="mono" style={{ fontSize: 10.5, color: INK_MUTE }}>
          saved {ago(w.modified_ms)} · {(w.bytes / 1024).toFixed(1)}KB
        </span>
        <div style={{ flex: 1 }} />
        <button className="ws-primary" onClick={() => void go()} disabled={busy}>
          {busy ? "Importing…" : "Import into Qamba"}
        </button>
      </div>

      <p style={{ fontSize: 12.5, color: "#c7cddb", margin: "10px 0 0", maxWidth: 680 }}>
        This is ComfyUI's copy, in its own workflows folder. Importing converts it to the
        API format the workers execute, tags the slots the studio writes into (prompt, seed,
        size, start frame, output) and files it under <b>Imported</b> — where it can be
        picked in the composer and rendered in the cloud or on this machine.
      </p>
      <p style={{ fontSize: 12, color: INK_MUTE, margin: "8px 0 0", maxWidth: 680 }}>
        It never edits the template it may have come from. The bundled graphs are
        parameterised by node CLASS, which only holds for graphs this studio wrote — an
        edited one would keep rendering and quietly stop taking the prompt. An imported
        graph is driven by its tagged slots instead, which is why the round trip lands here.
      </p>

      {(note || err) && (
        <div style={{
          marginTop: 10, fontSize: 12, padding: "8px 10px", borderRadius: 10,
          color: err ? "#f0b9a4" : "#c7cddb",
          background: err ? "rgba(232,115,74,0.09)" : "rgba(255,255,255,0.035)",
          border: `1px solid ${err ? "rgba(232,115,74,0.28)" : "rgba(255,255,255,0.07)"}`,
        }}>{err ?? note}</div>
      )}
    </div>
  );
}

/**
 * A LOCAL RECIPE — the desktop's other renderer.
 *
 * The pod resolves a JSON template; the desktop's composer lane builds its
 * graph in TypeScript, from the same engine catalogue the download screen
 * offers. Both are "the workflow this model renders on", and only one of them
 * is a file — which is why "I have Wan installed and there is no workflow for
 * it" was a correct observation about a page that only listed files.
 */
function LocalRecipeDetail({ row, onPick, have }: {
  row: LocalRecipeRow;
  onPick: (sel: string) => void;
  have: TemplateRow[];
}) {
  const sampling = (s: LocalRecipeRow["sampling"]) =>
    `${s.steps} steps · cfg ${s.cfg} · ${s.sampler}/${s.scheduler}`
    + (s.shift ? ` · shift ${s.shift}` : "");
  const base = sampling(row.sampling);

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
      <div className="ws-card ns-l1" style={{ borderRadius: 18 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
          <FileJson size={14} style={{ color: INK_MUTE }} />
          <span className="mono" style={{ fontSize: 13.5, fontWeight: 600 }}>{row.family}</span>
          <Badge color={INK_MUTE}>built in code</Badge>
          <Badge color="#aa5bde">{row.kind}</Badge>
          {row.installed > 0
            ? <Badge color={C_OK}>{row.installed} of {row.variants.length} on this machine</Badge>
            : <Badge color={INK_MUTE}>not downloaded</Badge>}
          <div style={{ flex: 1 }} />
          <span className="mono" style={{ fontSize: 10.5, color: INK_MUTE }}>{row.license}</span>
        </div>

        <p style={{ fontSize: 12.5, color: "#c7cddb", margin: "10px 0 0", maxWidth: 680 }}>
          {row.name} renders here with no template at all — the graph is built in code and
          submitted straight to your own ComfyUI, which is why the template list above does
          not mention it. Blocks are the other half: those go through the templates on the
          left.
        </p>

        {row.portedFrom.length > 0 && (
          <div style={{ marginTop: 12 }}>
            <div className="mono" style={{ fontSize: 10, color: INK_MUTE, marginBottom: 6 }}>
              PORTED FROM
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
              {row.portedFrom.map((src) => {
                const file = src.startsWith("workflows/") ? src.slice("workflows/".length) : null;
                const listed = file && have.some((r) => r.parsed.name === file);
                return listed ? (
                  <button key={src} onClick={() => onPick(file!)} title="show this template">
                    <Badge color="#458de8">{file}</Badge>
                  </button>
                ) : <Badge key={src} color={INK_MUTE}>{src}</Badge>;
              })}
            </div>
          </div>
        )}

        <div style={{ marginTop: 12, display: "flex", gap: 8, fontSize: 12 }}>
          <span style={{ color: INK_MUTE, width: 96, flex: "none" }}>Recipe</span>
          <span className="mono" style={{ fontSize: 11.5 }}>{base}</span>
        </div>
        <div style={{ display: "flex", gap: 8, fontSize: 12, paddingTop: 3 }}>
          <span style={{ color: INK_MUTE, width: 96, flex: "none" }}>Modes</span>
          <span style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
            {row.modes.map((m) => <Badge key={m} color="#458de8">{m}</Badge>)}
          </span>
        </div>
      </div>

      <div className="ws-card ns-l1" style={{ borderRadius: 18 }}>
        <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 4 }}>Variants</div>
        <p style={{ fontSize: 11.5, color: INK_MUTE, margin: "0 0 8px", maxWidth: 700 }}>
          What the engine window offers for this family. A variant's sampling is shown only
          where it DIFFERS from the recipe above — a distillation is not sampled like a base
          model, and quoting one number for both would be wrong for one of them.
        </p>
        {row.variants.map((v) => {
          const own = sampling(v.sampling);
          return (
            <div key={v.id} style={{
              display: "flex", gap: 8, alignItems: "baseline", padding: "4px 0",
              borderTop: "1px solid rgba(255,255,255,0.05)", fontSize: 12,
            }}>
              {v.installed
                ? <Check size={12} style={{ color: C_OK, flex: "none" }} />
                : <Minus size={12} style={{ color: INK_MUTE, flex: "none" }} />}
              <span className="mono" style={{ fontSize: 11.5, width: 150, flex: "none" }}>
                {v.id}
              </span>
              <span style={{ color: INK_MUTE, minWidth: 0 }}>
                {v.label}{own !== base && <span className="mono"> · {own}</span>}
              </span>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function TemplateDetail({ row, mm, tier, portedInto, catalogByKey, raw, showRaw, onToggleRaw }: {
  row: TemplateRow;
  mm: ModelMap;
  tier: string;
  /** the local recipes ported FROM this template, when any */
  portedInto: string[] | null;
  catalogByKey: Map<string, ModelCatalogRow[]>;
  raw: string;
  showRaw: boolean;
  onToggleRaw: () => void;
}) {
  const p = row.parsed;

  // Which (model, mode) the contract is evaluated against. A template shared
  // by six H3 variants is checked against the first — they differ in
  // checkpoint and LoRA, not in graph shape — and an override template that
  // no mode names carries its own `as` hint.
  const use = row.uses[0];
  const asModel = row.handler?.as?.model ?? use?.model;
  const asMode = row.handler?.as?.mode ?? use?.mode;
  const spec = asModel ? mm[tier]?.models?.[asModel] : undefined;

  const contract: ContractRow[] = useMemo(() => {
    if (p.format !== "api") return [];
    if (row.dialect === "node-ids" && row.handler?.pins) return pinContract(p.nodes, row.handler.pins);
    if (row.dialect === "substitution") return substitutionContract(p);
    if (row.dialect === "resolve") return contractOf(p.nodes, { mode: asMode, model: spec });
    return [];
  }, [p, row, asMode, spec]);

  const risks = contract.filter((c) => c.status === "risk").length;

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
      <div className="ws-card ns-l1" style={{ borderRadius: 18 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
          <Workflow size={14} style={{ color: INK_MUTE }} />
          <span className="mono" style={{ fontSize: 13.5, fontWeight: 600 }}>{p.name}</span>
          <Badge color={HEALTH_COLOR[row.health]}>{HEALTH_LABEL[row.health]}</Badge>
          {p.format !== "api" && <Badge color={C_BROKEN}>{p.format} format</Badge>}
          {row.dialect && (
            <Badge color="#aa5bde" title="how this template gets its parameters">
              {row.dialect}
            </Badge>
          )}
          {p.format === "api" && (
            <span className="mono" style={{ fontSize: 10.5, color: INK_MUTE }}>
              {p.nodes.length} nodes · {(p.bytes / 1024).toFixed(1)}KB
            </span>
          )}
          <div style={{ flex: 1 }} />
          {p.format === "api" && (
            <EditInComfyButton name={p.name} source={{ api: apiOf(raw) }} />
          )}
          <CopyButton text={raw} label="Copy JSON" />
        </div>

        {row.note && (
          <div style={{
            marginTop: 10, fontSize: 12, padding: "8px 10px", borderRadius: 10,
            color: row.health === "broken" ? "#f0b9a4" : "#c7cddb",
            background: row.health === "broken" ? "rgba(232,115,74,0.09)" : "rgba(255,255,255,0.035)",
            border: `1px solid ${row.health === "broken" ? "rgba(232,115,74,0.28)" : "rgba(255,255,255,0.07)"}`,
          }}>{row.note}</div>
        )}

        {/* Who runs it. This is the whole question the page exists to answer. */}
        <div style={{ marginTop: 12 }}>
          <div className="mono" style={{ fontSize: 10, color: INK_MUTE, marginBottom: 6 }}>USED BY</div>
          {row.uses.length === 0 && !row.handler && (
            <span style={{ fontSize: 12, color: INK_MUTE }}>
              nothing on this tier — no model and no handler names this file
            </span>
          )}
          {/* …but "nobody resolves it" is not "nobody uses it". The desktop's
              Wan renders through a TypeScript port of exactly this file. */}
          {portedInto && (
            <div style={{ fontSize: 12, color: "#c7cddb", marginTop: 6 }}>
              Ported into{" "}
              {portedInto.map((f) => <Badge key={f} color="#458de8">{f}</Badge>)}
              {" — "}<span style={{ color: INK_MUTE }}>
                that graph is built in code for this machine&rsquo;s own renders, so this file is
                its source rather than dead weight.
              </span>
            </div>
          )}
          <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
            {row.uses.map((u) => {
              const picks = catalogByKey.get(u.model) ?? [];
              return (
                <Badge key={`${u.model}/${u.mode}`} color="#458de8"
                  title={[
                    u.checkpoint ? `checkpoint: ${u.checkpoint}` : null,
                    picks.length ? `picker: ${picks.map((c) => c.display_name).join(", ")}` : null,
                  ].filter(Boolean).join("\n")}>
                  {u.model} · {u.mode}
                </Badge>
              );
            })}
          </div>
          {row.handler && (
            <div className="mono" style={{ fontSize: 11, color: "#c7cddb", marginTop: 6 }}>
              {row.handler.where}
            </div>
          )}
        </div>

        {p.comment && (
          <p style={{
            marginTop: 12, marginBottom: 0, fontSize: 11.5, color: INK_MUTE,
            lineHeight: 1.55, maxWidth: 760,
          }}>{p.comment}</p>
        )}
      </div>

      {contract.length > 0 && (
        <div className="ws-card ns-l1" style={{ borderRadius: 18 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
            <span style={{ fontSize: 13, fontWeight: 600 }}>
              {row.dialect === "resolve" ? "What resolve() can set"
                : row.dialect === "substitution" ? "Text substitutions"
                : "Node ids the handler writes into"}
            </span>
            {risks > 0
              ? <Badge color={C_RISK}>{risks} dropped</Badge>
              : <Badge color={C_OK}>all wired</Badge>}
          </div>
          <p style={{ fontSize: 11.5, color: INK_MUTE, margin: "0 0 8px", maxWidth: 700 }}>
            {row.dialect === "resolve"
              ? "resolve() rewrites nodes by class_type. A parameter with no node to write into is "
                + "accepted from the job and silently dropped — the template's own literal renders."
              : row.dialect === "substitution"
              ? "The handler replaces these markers in the raw text before parsing, so the file is "
                + "only valid JSON afterwards."
              : "The handler indexes nodes by id. Renumbering this graph — which re-exporting it "
                + "from ComfyUI does freely — moves the write or raises."}
          </p>
          {contract.map((c) => <ContractLine key={c.id} row={c} />)}
        </div>
      )}

      {p.format === "api" && (
        <div className="ws-card ns-l1" style={{ borderRadius: 18 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 8 }}>
            <span style={{ fontSize: 13, fontWeight: 600 }}>Graph</span>
            <div style={{ flex: 1 }} />
            <button className="ws-actbtn" onClick={onToggleRaw}
              style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 11.5 }}>
              <FileJson size={12} />{showRaw ? "Hide raw JSON" : "Raw JSON"}
            </button>
          </div>
          {showRaw ? (
            <pre className="mono ns-scroll" style={{
              fontSize: 10.5, lineHeight: 1.5, color: "#c7cddb", margin: 0,
              maxHeight: 460, overflow: "auto", whiteSpace: "pre",
            }}>{raw}</pre>
          ) : (
            <div style={{ overflowX: "auto" }}>
              <table className="mono" style={{ fontSize: 11, borderCollapse: "collapse", width: "100%" }}>
                <tbody>
                  {p.nodes.map((n) => (
                    <tr key={n.id} style={{ borderTop: "1px solid rgba(255,255,255,0.05)" }}>
                      <td style={{ padding: "5px 8px 5px 0", color: INK_MUTE, verticalAlign: "top", width: 30 }}>
                        #{n.id}
                      </td>
                      <td style={{ padding: "5px 10px 5px 0", verticalAlign: "top", whiteSpace: "nowrap" }}>
                        {n.class_type}
                      </td>
                      <td style={{ padding: "5px 0", color: INK_MUTE, verticalAlign: "top" }}>
                        {inputSummary(n)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
